-- =====================================================================================================
-- Generated by Data Dictionary Version 1.0.0.0
-- Date: 13 July 2016 08:37
-- Profile: 1516 Test Harness Calculation
-- Rulebase Version: ILR SFA Calculation 1617, Drop 000, Version 1617.02
-- =====================================================================================================
use [$(IntrajobDatabase)]
go
insert into
	[Input].[LearningProvider]
		(
			[LearningProvider_Id],
			[UKPRN]
		)
select
	[PK_LearningProvider],
	[UKPRN]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearningProvider]
go

insert into
	[Input].[Learner]
		(
			[Learner_Id],
			[LearnRefNumber],
			[DateOfBirth]
		)
select
	[PK_Learner],
	[LearnRefNumber],
	[DateOfBirth]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[Learner]
go

insert into
	[Input].[LearningDelivery]
		(
			[LearningDelivery_Id],
			[Learner_Id],
			[AimSeqNumber],
			[AchDate],
			[AddHours],
			[AimType],
			[CompStatus],
			[EmpOutcome],
			[LearnAimRef],
			[FworkCode],
			[ProgType],
			[PwayCode],
			[LearnActEndDate],
			[LearnPlanEndDate],
			[LearnStartDate],
			[OrigLearnStartDate],
			[OtherFundAdj],
			[Outcome],
			[PriorLearnFundAdj],
			[DelLocPostCode],
			[FundModel]
		)
select
	[PK_LearningDelivery],
	[FK_Learner],
	[AimSeqNumber],
	[AchDate],
	[AddHours],
	[AimType],
	[CompStatus],
	[EmpOutcome],
	[LearnAimRef],
	[FworkCode],
	[ProgType],
	[PwayCode],
	[LearnActEndDate],
	[LearnPlanEndDate],
	[LearnStartDate],
	[OrigLearnStartDate],
	[OtherFundAdj],
	[Outcome],
	[PriorLearnFundAdj],
	[DelLocPostCode],
	[FundModel]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearningDelivery]
go

insert into
	[Input].[LearningDeliveryFAM]
		(
			[LearningDeliveryFAM_Id],
			[LearningDelivery_Id],
			[LearnDelFAMType],
			[LearnDelFAMDateFrom],
			[LearnDelFAMCode],
			[LearnDelFAMDateTo]
		)
select
	[PK_LearningDeliveryFAM],
	[FK_LearningDelivery],
	[LearnDelFAMType],
	[LearnDelFAMDateFrom],
	[LearnDelFAMCode],
	[LearnDelFAMDateTo]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearningDeliveryFAM]
go

insert into
	[Input].[LearnerEmploymentStatus]
		(
			[LearnerEmploymentStatus_Id],
			[Learner_Id],
			[DateEmpStatApp],
			[EmpId]
		)
select
	[PK_LearnerEmploymentStatus],
	[FK_Learner],
	[DateEmpStatApp],
	[EmpId]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearnerEmploymentStatus]
go

insert into
	[Input].[LearnerContact]
		(
			[LearnerContact_Id],
			[Learner_Id],
			[LocType],
			[ContType],
			[PostCode]
		)
select
	[PK_LearnerContact],
	[FK_Learner],
	[LocType],
	[ContType],
	[PostCode]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearnerContact]
go

