-- =====================================================================================================
-- Generated by Data Dictionary Version 1.0.0.0
-- Date: 13 July 2016 15:37
-- Profile: 1516 Test Harness Calculation
-- Rulebase Version: ILR 24+ Loans Calculation 1617, Drop 000, Version 1617.03
-- =====================================================================================================
use [$(IntrajobDatabase)]
go
insert into
	[Valid].[LearningProvider]
		(
			[UKPRN]
		)
select
	[UKPRN]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearningProvider]
where
	[LearningProvider].[UKPRN]=$(UKPRN)
go

insert into
	[Valid].[Learner]
		(
			[LearnRefNumber]
		)
select
	[LearnRefNumber]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[Learner]
where
	[Learner].[UKPRN]=$(UKPRN)
go

insert into
	[Valid].[LearningDelivery]
		(
			[LearnRefNumber],
			[AimSeqNumber],
			[CompStatus],
			[LearnActEndDate],
			[LearnAimRef],
			[LearnPlanEndDate],
			[LearnStartDate],
			[LrnDelFAM_ADL],
			[LrnDelFAM_RES],
			[OrigLearnStartDate],
			[OtherFundAdj],
			[Outcome],
			[PriorLearnFundAdj],
			[DelLocPostCode],
			[FundModel]
		)
select
	[LearnRefNumber],
	[AimSeqNumber],
	[CompStatus],
	[LearnActEndDate],
	[LearnAimRef],
	[LearnPlanEndDate],
	[LearnStartDate],
	[LrnDelFAM_ADL],
	[LrnDelFAM_RES],
	[OrigLearnStartDate],
	[OtherFundAdj],
	[Outcome],
	[PriorLearnFundAdj],
	[DelLocPostCode],
	[FundModel]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearningDeliveryDenorm] LearningDelivery
where
	[LearningDelivery].[UKPRN]=$(UKPRN)
go

insert into
	[Valid].[LearningDeliveryFAM]
		(
			[LearnDelFAMCode],
			[LearnDelFAMDateFrom],
			[LearnDelFAMDateTo],
			[LearnDelFAMType]
		)
select
	[LearnDelFAMCode],
	[LearnDelFAMDateFrom],
	[LearnDelFAMDateTo],
	[LearnDelFAMType]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearningDeliveryFAM]
where
	[LearningDeliveryFAM].[UKPRN]=$(UKPRN)
go

