-- =====================================================================================================
-- Generated by Data Dictionary Version 1.0.0.0
-- Date: 31 May 2017 10:51
-- Profile: DCSS Validation
-- Rulebase Version: NCS Validation 1516 1516, Version 1516.07
-- =====================================================================================================
if not exists(select schema_id from sys.schemas where name='Rulebase')
	exec('create schema Rulebase')
go
if object_id('[Rulebase].[NCS_VAL_Cases]','u') is not null
	drop table [Rulebase].[NCS_VAL_Cases]
create table [Rulebase].[NCS_VAL_Cases]
	(
		[Customer_Id] [int] primary key,
		[CaseData] [xml] not null
	)
go
if object_id('[Rulebase].[NCS_VAL_global]','u') is not null
	drop table [Rulebase].[NCS_VAL_global]
create table [Rulebase].[NCS_VAL_global]
	(
		[TouchpointID] varchar(100),
		[RulebaseVersion] varchar(10),
	)
go
if object_id('[Rulebase].[NCS_VAL_ValidationError]','u') is not null
	drop table [Rulebase].[NCS_VAL_ValidationError]
create table [Rulebase].[NCS_VAL_ValidationError]
	(
		[ActionPlanID] varchar(100),
		[ErrorMessage] varchar(2000),
		[RuleId] varchar(100),
		[Severity] varchar(10),
		[TouchpointCustomerID] varchar(100),
		[TouchpointID] varchar(100),
		[ValidationErrorID] varchar(2500)
	)
go
