-- =====================================================================================================
-- Generated by Data Dictionary Version 1.0.0.0
-- Date: 06 April 2016 14:54
-- Profile: 1516 Test Harness Calculation
-- Rulebase Version: DCSS 1516 EFA Calculation 1516, Drop 000, Version 1516.06
-- =====================================================================================================
use [$(IntrajobDatabase)]
go
insert into
	[Input].[LearningProvider]
		(
			[LearningProvider_Id],
			[UKPRN]
		)
select
	[PK_LearningProvider],
	[UKPRN]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearningProvider]
go

insert into
	[Input].[Learner]
		(
			[Learner_Id],
			[LearnRefNumber],
			[DateOfBirth],
			[EngGrade],
			[MathGrade],
			[PlanEEPHours],
			[PlanLearnHours],
			[ULN]
		)
select
	[PK_Learner],
	[LearnRefNumber],
	[DateOfBirth],
	[EngGrade],
	[MathGrade],
	[PlanEEPHours],
	[PlanLearnHours],
	[ULN]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[Learner]
go

insert into
	[Input].[LearnerFAM]
		(
			[LearnerFAM_Id],
			[LearnFAMType],
			[Learner_Id],
			[LearnFAMCode]
		)
select
	[PK_LearnerFAM],
	[LearnFAMType],
	[FK_Learner],
	[LearnFAMCode]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearnerFAM]
go

insert into
	[Input].[LearningDelivery]
		(
			[LearningDelivery_Id],
			[AimSeqNumber],
			[Learner_Id],
			[AimType],
			[CompStatus],
			[FundModel],
			[LearnActEndDate],
			[LearnAimRef],
			[LearnPlanEndDate],
			[LearnStartDate],
			[ProgType]
		)
select
	[PK_LearningDelivery],
	[AimSeqNumber],
	[FK_Learner],
	[AimType],
	[CompStatus],
	[FundModel],
	[LearnActEndDate],
	[LearnAimRef],
	[LearnPlanEndDate],
	[LearnStartDate],
	[ProgType]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearningDelivery]
go

insert into
	[Input].[LearningDeliveryFAM]
		(
			[LearningDeliveryFAM_Id],
			[LearnDelFAMType],
			[LearningDelivery_Id],
			[LearnDelFAMDateFrom],
			[LearnDelFAMCode]
		)
select
	[PK_LearningDeliveryFAM],
	[LearnDelFAMType],
	[FK_LearningDelivery],
	[LearnDelFAMDateFrom],
	[LearnDelFAMCode]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearningDeliveryFAM]
go

insert into
	[Input].[DPOutcome]
		(
			[DPOutcome_Id],
			[OutType],
			[LearnerDestinationandProgression_Id],
			[OutCode],
			[OutStartDate]
		)
select
	[PK_DPOutcome],
	[OutType],
	[FK_LearnerDestinationandProgression],
	[OutCode],
	[OutStartDate]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[DPOutcome]
go

insert into
	[Input].[LearnerDestinationandProgression]
		(
			[LearnerDestinationandProgression_Id],
			[LearnRefNumber]
		)
select
	[PK_LearnerDestinationandProgression],
	[LearnRefNumber]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearnerDestinationandProgression]
go

