use [$(IntrajobDatabase)]
GO
if object_id('[Rulebase].[EFA_Get_Cases]','p') is not null
	drop procedure [Rulebase].[EFA_Get_Cases]
GO
-- =====================================================================================================
-- Generated by Data Dictionary Version 1.0.0.0
-- Date: 06 April 2016 10:54
-- Profile: 1516 Test Harness Calculation
-- Rulebase Version: DCSS 1516 EFA Calculation 1516, Drop 000, Version 1516.06
-- =====================================================================================================
create procedure [Rulebase].[EFA_Get_Cases] as

	begin
		set nocount on
		select
			CaseData
		from
			[Rulebase].[EFA_Cases]
	end
GO
if object_id('[Rulebase].[EFA_Insert_Cases]','p') is not null
	drop procedure [Rulebase].[EFA_Insert_Cases]
GO
-- =====================================================================================================
-- Generated by Data Dictionary Version 1.0.0.0
-- Date: 06 April 2016 10:54
-- Profile: 1516 Test Harness Calculation
-- Rulebase Version: DCSS 1516 EFA Calculation 1516, Drop 000, Version 1516.06
-- =====================================================================================================
create procedure [Rulebase].[EFA_Insert_Cases] as

	begin
		set nocount on

		insert into
			[Rulebase].[EFA_Cases]
			(
				[LearnRefNumber],
				CaseData
			)
		select
			ControllingTable.[LearnRefNumber],
			convert(xml,
				(
					select
						[LearningProvider_ORG_Funding_EFA_Area_Cost].[FundingFactorValue] as [@AreaCostFactor1618],
						[LearningProvider_ORG_Funding_EFA_Disadvantage].[FundingFactorValue] as [@DisadvantageProportion],
						[LARS_Current_Version].[CurrentVersion] as [@LARSVersion],
						[LearningProvider_ORG_Funding_EFA_PWF].[FundingFactorValue] as [@ProgrammeWeighting],
						[LearningProvider_ORG_Funding_EFA_Retention].[FundingFactorValue] as [@RetentionFactor],
						case when [LearningProvider_ORG_Funding_EFA_Specialist_Resources].[FundingFactorValue] = '1' then 'true' else 'false' end as [@SpecialistResources],
						[LearningProvider].[UKPRN] as [@UKPRN],
						(
							select
								[Learner].[DateOfBirth] as [@DateOfBirth],
								[Learner].[EngGrade] as [@EngGrade],
								[Learner].[LearnRefNumber] as [@LearnRefNumber],
								[Learner].[LrnFAM_ECF] as [@LrnFAM_ECF],
								[Learner].[LrnFAM_EDF1] as [@LrnFAM_EDF1],
								[Learner].[LrnFAM_EDF2] as [@LrnFAM_EDF2],
								[Learner].[LrnFAM_EHC] as [@LrnFAM_EHC],
								[Learner].[LrnFAM_HNS] as [@LrnFAM_HNS],
								[Learner].[LrnFAM_LDA] as [@LrnFAM_LDA],
								[Learner].[LrnFAM_MCF] as [@LrnFAM_MCF],
								[Learner].[MathGrade] as [@MathGrade],
								[Learner].[PlanEEPHours] as [@PlanEEPHours],
								[Learner].[PlanLearnHours] as [@PlanLearnHours],
								case when Learner.HomePostcode = 'ZZ99 9ZZ' then [Learner_PostcodeDisadvantage_EFA_Current].[EFA_Uplift] else [Learner_PostcodeDisadvantage].[EFA_Uplift] end as [@PostcodeDisadvantageUplift],
								[Learner].[ULN] as [@ULN],
								(
									select
										[LearningDelivery].[AimSeqNumber] as [@AimSeqNumber],
										[LearningDelivery].[AimType] as [@AimType],
										[LARS_LearningDelivery].[AwardOrgCode] as [@AwardOrgCode],
										[LearningDelivery].[CompStatus] as [@CompStatus],
										[LARS_LearningDelivery].[EFACOFType] as [@EFACOFType],
										[LearningDelivery].[FundModel] as [@FundModel],
										[LearningDelivery].[LearnActEndDate] as [@LearnActEndDate],
										[LearningDelivery].[LearnAimRef] as [@LearnAimRef],
										[LARS_LearningDelivery].[LearnAimRefTitle] as [@LearnAimRefTitle],
										[LARS_LearningDelivery].[LearnAimRefType] as [@LearnAimRefType],
										[LearningDelivery].[LearnPlanEndDate] as [@LearnPlanEndDate],
										[LearningDelivery].[LearnStartDate] as [@LearnStartDate],
										[LearningDelivery].[LrnDelFAM_LDM1] as [@LrnDelFAM_LDM1],
										[LearningDelivery].[LrnDelFAM_LDM2] as [@LrnDelFAM_LDM2],
										[LearningDelivery].[LrnDelFAM_LDM3] as [@LrnDelFAM_LDM3],
										[LearningDelivery].[LrnDelFAM_LDM4] as [@LrnDelFAM_LDM4],
										[LearningDelivery].[LrnDelFAM_SOF] as [@LrnDelFAM_SOF],
										[LearningDelivery].[ProgType] as [@ProgType],
										[LARS_LearningDelivery].[SectorSubjectAreaTier2] as [@SectorSubjectAreaTier2],
										(
											select
												[LARS_Validity].[ValidityCategory] as [@ValidityCategory],
												[LARS_Validity].[LastNewStartDate] as [@ValidityLastNewStartDate],
												[LARS_Validity].[StartDate] as [@ValidityStartDate]
											from
												[$(LARS)].[$(LARS_Schema)].[LARS_Validity]
											where
												[LARS_Validity].[LearnAimRef]=[LearningDelivery].[LearnAimRef]
											for xml path ('LearningDeliveryLARSValidity'), type
										)
									from
										[Valid].[LearningDelivery]
										left join [$(LARS)].[$(LARS_Schema)].[LARS_LearningDelivery]
											on [LARS_LearningDelivery].[LearnAimRef]=[LearningDelivery].[LearnAimRef]
									where
										[LearningDelivery].[LearnRefNumber] = [Learner].[LearnRefNumber]
										and [LearningDelivery].[FundModel]=25
									for xml path ('LearningDelivery'), type
								),
								(
									select
										[DPOutcome].[OutCode] as [@OutCode],
										[DPOutcome].[OutType] as [@OutType]
									from
										[Valid].[DPOutcome]
									where
										[DPOutcome].[LearnRefNumber] = [Learner].[LearnRefNumber]
									for xml path ('DPOutcome'), type
								)
							from
								[Valid].[Learner]
								left join [$(PostcodeFactors)].[$(PostcodeFactors_Schema)].[PostcodeDisadvantage] as [Learner_PostcodeDisadvantage]
									on [Learner_PostcodeDisadvantage].[Postcode]=[Learner].[HomePostcode]
								left join [$(PostcodeFactors)].[$(PostcodeFactors_Schema)].[PostcodeDisadvantage] as [Learner_PostcodeDisadvantage_EFA_Current]
									on [Learner_PostcodeDisadvantage_EFA_Current].[Postcode]=[Learner].[CurrentPostcode]
							where
								[Learner].[LearnRefNumber] = [ControllingTable].[LearnRefNumber]
							for xml path ('Learner'), type
						)
					from
						[Valid].[LearningProvider]
						cross join [$(LARS)].[$(LARS_Schema)].[LARS_Current_Version]
						left join [$(Org)].[$(Org_Schema)].[ORG_Funding] as [LearningProvider_ORG_Funding_EFA_Area_Cost]
							on [LearningProvider_ORG_Funding_EFA_Area_Cost].[UKPRN]=[LearningProvider].[UKPRN]
							and [LearningProvider_ORG_Funding_EFA_Area_Cost].[FundingFactorType]='EFA 16-19'
							and [LearningProvider_ORG_Funding_EFA_Area_Cost].[FundingFactor]='HISTORIC AREA COST FACTOR'
							and [LearningProvider_ORG_Funding_EFA_Area_Cost].[EffectiveFrom]='1-Aug-2015'
						left join [$(Org)].[$(Org_Schema)].[ORG_Funding] as [LearningProvider_ORG_Funding_EFA_Disadvantage]
							on [LearningProvider_ORG_Funding_EFA_Disadvantage].[UKPRN]=[LearningProvider].[UKPRN]
							and [LearningProvider_ORG_Funding_EFA_Disadvantage].[FundingFactorType]='EFA 16-19'
							and [LearningProvider_ORG_Funding_EFA_Disadvantage].[FundingFactor]='HISTORIC DISADVANTAGE FUNDING PROPORTION'
							and [LearningProvider_ORG_Funding_EFA_Disadvantage].[EffectiveFrom]='1-Aug-2015'
						left join [$(Org)].[$(Org_Schema)].[ORG_Funding] as [LearningProvider_ORG_Funding_EFA_PWF]
							on [LearningProvider_ORG_Funding_EFA_PWF].[UKPRN]=[LearningProvider].[UKPRN]
							and [LearningProvider_ORG_Funding_EFA_PWF].[FundingFactorType]='EFA 16-19'
							and [LearningProvider_ORG_Funding_EFA_PWF].[FundingFactor]='HISTORIC PROGRAMME COST WEIGHTING FACTOR'
							and [LearningProvider_ORG_Funding_EFA_PWF].[EffectiveFrom]='1-Aug-2015'
						left join [$(Org)].[$(Org_Schema)].[ORG_Funding] as [LearningProvider_ORG_Funding_EFA_Retention]
							on [LearningProvider_ORG_Funding_EFA_Retention].[UKPRN]=[LearningProvider].[UKPRN]
							and [LearningProvider_ORG_Funding_EFA_Retention].[FundingFactorType]='EFA 16-19'
							and [LearningProvider_ORG_Funding_EFA_Retention].[FundingFactor]='HISTORIC RETENTION FACTOR'
							and [LearningProvider_ORG_Funding_EFA_Retention].[EffectiveFrom]='1-Aug-2015'
						left join [$(Org)].[$(Org_Schema)].[ORG_Funding] as [LearningProvider_ORG_Funding_EFA_Specialist_Resources]
							on [LearningProvider_ORG_Funding_EFA_Specialist_Resources].[UKPRN]=[LearningProvider].[UKPRN]
							and [LearningProvider_ORG_Funding_EFA_Specialist_Resources].[FundingFactorType]='EFA 16-19'
							and [LearningProvider_ORG_Funding_EFA_Specialist_Resources].[FundingFactor]='SPECIALIST RESOURCES'
					for xml path ('global'), type
				)
			)
		from
			[Valid].[Learner] ControllingTable
			inner join
				(
					select distinct
						[LearningDelivery].[LearnRefNumber]
					from
						[Valid].[LearningDelivery]
					where
						[LearningDelivery].[FundModel]=25
				) [Filter_LearningDelivery]
				on [Filter_LearningDelivery].[LearnRefNumber]=[ControllingTable].[LearnRefNumber]
	end
GO
if object_id('[Rulebase].[EFA_Insert_global]','p') is not null
	drop procedure [Rulebase].[EFA_Insert_global]
GO
-- =====================================================================================================
-- Generated by Data Dictionary Version 1.0.0.0
-- Date: 06 April 2016 10:54
-- Profile: 1516 Test Harness Calculation
-- Rulebase Version: DCSS 1516 EFA Calculation 1516, Drop 000, Version 1516.06
-- =====================================================================================================
create procedure [Rulebase].[EFA_Insert_global]
	(
		@UKPRN int,
		@LARSVersion varchar(50),
		@OrgVersion varchar(50),
		@PostcodeDisadvantageVersion varchar(50),
		@RulebaseVersion varchar(10)
	)
as
	begin
		set nocount on
		insert into
			[Rulebase].[EFA_global]
		values (
			@UKPRN,
			@LARSVersion,
			@OrgVersion,
			@PostcodeDisadvantageVersion,
			@RulebaseVersion
		)
	end
GO
if object_id('[Rulebase].[EFA_Insert_Learner]','p') is not null
	drop procedure [Rulebase].[EFA_Insert_Learner]
GO
-- =====================================================================================================
-- Generated by Data Dictionary Version 1.0.0.0
-- Date: 06 April 2016 10:54
-- Profile: 1516 Test Harness Calculation
-- Rulebase Version: DCSS 1516 EFA Calculation 1516, Drop 000, Version 1516.06
-- =====================================================================================================
create procedure [Rulebase].[EFA_Insert_Learner]
	(
		@LearnRefNumber varchar(12),
		@AcadMonthPayment int,
		@AcadProg bit,
		@ActualDaysILCurrYear int,
		@AreaCostFact1618Hist decimal(10,5),
		@Block1DisadvUpliftNew decimal(10,5),
		@Block2DisadvElementsNew decimal(10,5),
		@ConditionOfFundingEnglish varchar(100),
		@ConditionOfFundingMaths varchar(100),
		@CoreAimSeqNumber int,
		@FullTimeEquiv decimal(10,5),
		@FundLine varchar(100),
		@LearnerActEndDate date,
		@LearnerPlanEndDate date,
		@LearnerStartDate date,
		@NatRate decimal(10,5),
		@OnProgPayment decimal(10,5),
		@PlannedDaysILCurrYear int,
		@ProgWeightHist decimal(10,5),
		@ProgWeightNew decimal(10,5),
		@PrvDisadvPropnHist decimal(10,5),
		@PrvRetentFactHist decimal(10,5),
		@RateBand varchar(50),
		@RetentNew decimal(10,5),
		@StartFund bit,
		@ThresholdDays int
	)
as
	begin
		set nocount on
		insert into
			[Rulebase].[EFA_Learner]
		values (
			@LearnRefNumber,
			@AcadMonthPayment,
			@AcadProg,
			@ActualDaysILCurrYear,
			@AreaCostFact1618Hist,
			@Block1DisadvUpliftNew,
			@Block2DisadvElementsNew,
			@ConditionOfFundingEnglish,
			@ConditionOfFundingMaths,
			@CoreAimSeqNumber,
			@FullTimeEquiv,
			@FundLine,
			@LearnerActEndDate,
			@LearnerPlanEndDate,
			@LearnerStartDate,
			@NatRate,
			@OnProgPayment,
			@PlannedDaysILCurrYear,
			@ProgWeightHist,
			@ProgWeightNew,
			@PrvDisadvPropnHist,
			@PrvRetentFactHist,
			@RateBand,
			@RetentNew,
			@StartFund,
			@ThresholdDays
		)
	end
GO
