truncate table ErrorReference.ErrorMessageLookUp
insert into ErrorReference.ErrorMessageLookUp
(
	RuleName,
	Severity,
	ErrorMessage
)
values
	(	'Inconsistent UKPRN'	,	'E'	,	'The UKPRN in the file name does not match the providers UKPRN in the Hub'	)	,
	(	'Namespace Mismatch'	,	'E'	,	'ILR submissions must use the correct namespace'),
	(	'Entity_1'	,	'E'	,	'	There are no valid learners in either the Learner record or the Learner Destination and Progression record'),
	(	'Filename_1'	,	'E'	,	'The filename is not in the correct format'),
	(	'	Filename_2	'	,	'E'	,	'	A file with the same UKPRN, collection year and date/time combination has been received before	'	)	,
	(	'	Filename_4	'	,	'E'	,	'	The UKPRN is not valid	'	)	,
	(	'	Filename_5	'	,	'E'	,	'	The year of collection is not 1718	'	)	,
	(	'	Filename_6	'	,	'E'	,	'	The serial number is not a 2 digit number	'	)	,
	(	'	Filename_7	'	,	'	E	'	,	'	The serial number is 00	'	)	,
	(	'	Filename_8	'	,	'	E	'	,	'	The file date/time is after todays date/time	'	)	,
	(	'	Filename_9	'	,	'	E	'	,	'	The date/time of the file is earlier than a previous transmission for this collection	'	)	,
	(	'	Header_2	'	,	'	E	'	,	'	The file preparation date is after todays date	'	)	,
	(	'	Header_3	'	,	'	E	'	,	'	The UKPRN in the filename does not match the UKPRN in the Header	'	)	,
	(	'	UKPRN_03	'	,	'	E	'	,	'	The UKPRN is not the same as recorded in the Header	'	)	,
	(	'	UKPRN_05	'	,	'	E	'	,	'	There is no ESF funding relationship for this UKPRN	'	)	,
	(	'	UKPRN_06	'	,	'	E	'	,	'	There is no Adult Skills funding relationship for this UKPRN 	'	)	,
	(	'	UKPRN_08	'	,	'	E	'	,	'	There is no Advanced Learner Loans Bursary funding relationship for this UKPRN	'	)	,
	(	'	UKPRN_09	'	,	'	E	'	,	'	There is no apprenticeship funding relationship for this UKPRN	'	)	,
	(	'	UKPRN_10	'	,	'	E	'	,	'	There is no apprenticeship funding relationship for this UKPRN	'	)	,
	(	'	PrevUKPRN_01	'	,	'	E	'	,	'	The UKPRN is not valid	'	)	,
	(	'	PMUKPRN_01	'	,	'	E	'	,	'	The UKPRN is not valid	'	)	,
	(	'	ULN_02	'	,	'	W	'	,	'	This Unique learner number should not be used	'	)	,
	(	'	ULN_03	'	,	'	W	'	,	'	This Unique learner number should not be used	'	)	,
	(	'	ULN_04	'	,	'	E	'	,	'	This Unique learner number does not pass the checksum calculation	'	)	,
	(	'	ULN_05	'	,	'	E	'	,	'	This Unique learner number is not valid	'	)	,
	(	'	ULN_06	'	,	'	W	'	,	'	This Unique learner number should not be used 	'	)	,
	(	'	ULN_07	'	,	'	E	'	,	'	This Unique learner number must not be used	'	)	,
	(	'	ULN_09	'	,	'	W	'	,	'	This Unique learner number should not be used	'	)	,
	(	'	ULN_10	'	,	'	W	'	,	'	This Unique learner number should not be used 	'	)	,
	(	'	ULN_11	'	,	'	E	'	,	'	This Unique learner number must not be used	'	)	,
	(	'	ULN_12	'	,	'	E	'	,	'	This Unique learner number must not be used	'	)	,
	(	'	FamilyName_01	'	,	'	E	'	,	'	The learners Family name must be returned	'	)	,
	(	'	FamilyName_02	'	,	'	E	'	,	'	The learners Family name must be returned	'	)	,
	(	'	FamilyName_04	'	,	'	E	'	,	'	The Learners Family name must be returned	'	)	,
	(	'	GivenNames_01	'	,	'	E	'	,	'	The Learners Given names must be returned	'	)	,
	(	'	GivenNames_02	'	,	'	E	'	,	'	The Learners Given names must be returned	'	)	,
	(	'	GivenNames_04	'	,	'	E	'	,	'	The Learners Given names must be returned	'	)	,
	(	'	DateOfBirth_01	'	,	'	E	'	,	'	The Date of birth must be returned	'	)	,
	(	'	DateOfBirth_02	'	,	'	W	'	,	'	The Date of birth must be returned	'	)	,
	(	'	DateOfBirth_03	'	,	'	W	'	,	'	The learner is 100 or over	'	)	,
	(	'	DateOfBirth_04	'	,	'	E	'	,	'	The learner is 115 or over	'	)	,
	(	'	DateOfBirth_05	'	,	'	W	'	,	'	The learner is under 4	'	)	,
	(	'	DateOfBirth_06	'	,	'	W	'	,	'	The learner is under 13	'	)	,
	(	'	DateOfBirth_07	'	,	'	E	'	,	'	The learner is 25 or over and the Source of funding is the EFA	'	)	,
	(	'	DateOfBirth_10	'	,	'	W	'	,	'	The learner is not over the school leaving age	'	)	,
	(	'	DateOfBirth_12	'	,	'	E	'	,	'	The learner is under 19 and the Community Learning provision is PCDL or NLDC	'	)	,
	(	'	DateOfBirth_13	'	,	'	W	'	,	'	The learner is under 16 and is HEFCE funded 	'	)	,
	(	'	DateOfBirth_14	'	,	'	W	'	,	'	The learner is under 18	'	)	,
	(	'	DateOfBirth_20	'	,	'	E	'	,	'	The learner is under 19 and the Source of funding is not the EFA	'	)	,
	(	'	DateOfBirth_23	'	,	'	E	'	,	'	The Date of birth has not been returned	'	)	,
	(	'	DateOfBirth_24	'	,	'	E	'	,	'	The Unique learner number has been returned and the Date of birth has not been returned	'	)	,
	(	'	DateOfBirth_25	'	,	'	E	'	,	'	The learner is under 19	'	)	,
	(	'	DateOfBirth_41	'	,	'	W	'	,	'	The learner is under 19	'	)	,
	(	'	DateOfBirth_26	'	,	'	E	'	,	'	The learner is under 19 and financed by a Advanced Learner Loan	'	)	,
	(	'	DateOfBirth_27	'	,	'	E	'	,	'	The Learners Date of birth is on or after the start of the current teaching year	'	)	,
	(	'	DateOfBirth_28	'	,	'	W	'	,	'	The learner is under 19 and the Learning start date and Learning planned end date do not reach the minimum duration of an apprenticeship	'	)	,
	(	'	DateOfBirth_29	'	,	'	W	'	,	'	The learner is 19 or over and the Learning start date and Learning planned end date do not reach the minimum duration of an apprenticeship	'	)	,
	(	'	DateOfBirth_35	'	,	'	E	'	,	'	The learner is under 19 and the Learning start date and Learning planned end date do not reach the minimum duration of an apprenticeship	'	)	,
	(	'	DateOfBirth_36	'	,	'	E	'	,	'	The learner is 19 or over and the Learning start date and Learning planned end date do not reach the minimum duration of an apprenticeship	'	)	,
	(	'	DateOfBirth_37	'	,	'	E	'	,	'	The learner is 19 or over and the Learning start date and Learning planned end date do not reach the minimum duration for an apprenticeship	'	)	,
	(	'	DateOfBirth_38	'	,	'	E	'	,	'	The learner is under 19 and the Learning start date and Learning actual end date do not reach the minimum duration of an apprenticeship	'	)	,
	(	'	DateOfBirth_39	'	,	'	E	'	,	'	The learner is 19 or over and the Learning start date and Learning actual end date do not reach the minimum duration of an apprenticeship	'	)	,
	(	'	DateOfBirth_40	'	,	'	E	'	,	'	The learner is 19 or over and the Learning start date and Learning actual end date do not reach the minimum duration for an apprenticeship	'	)	,
	(	'	DateOfBirth_30	'	,	'	E	'	,	'	The learner is between 19 and 24 and has a Learning difficulty assessment or an Education health plan, and the Funding model and/or Source of funding is not the EFA	'	)	,
	(	'	DateOfBirth_32	'	,	'	E	'	,	'	The learning aim started on or after 1 August 2015 and the learner is 24 or over and the aim is Level 3 or above and the Funding model is Adult Skills	'	)	,
	(	'	DateOfBirth_34	'	,	'	E	'	,	'	The learner is recorded as a High Needs Student but there is no Learning difficulty assessment or Education health care plan recorded	'	)	,
	(	'	DateOfBirth_43	'	,	'	E	'	,	'	The learner is under 15	'	)	,
	(	'	DateOfBirth_44	'	,	'	E	'	,	'	The Learners age is outside of the age range described in the ESF Tender Specification	'	)	,
	(	'	DateOfBirth_46	'	,	'	E	'	,	'	The planned duration of the programme does not reach the required minimum duration for an apprenticeship standard	'	)	,
	(	'	DateOfBirth_47	'	,	'	E	'	,	'	The actual duration of the programme does not reach the required minimum duration for an apprenticeship standard	'	)	,
	(	'	DateOfBirth_48	'	,	'	W	'	,	'	The learner is not over the school leaving age	'	)	,
	(	'	DateOfBirth_49	'	,	'	E	'	,	'	The learning aim started on or after 1 August 2016 and the learner is 24 or over and the aim is Level 3 or above and the Funding model is Adult skills	'	)	,
	(	'	DateOfBirth_50	'	,	'	E	'	,	'	The learner must not start a traineeship programme until after 1 August of the academic year in which they turn 16	'	)	,
	(	'	DateOfBirth_51	'	,	'	E	'	,	'	The learners age is ineligible for a traineeship programme	'	)	,
	(	'	DateOfBirth_52	'	,	'	E	'	,	'	The programme does not reach the required minimum duration of an apprenticeship	'	)	,
	(	'	DateOfBirth_53	'	,	'	E	'	,	'	The programme does not reach the required minimum duration of an apprenticeship	'	)	,
	(	'	DateOfBirth_54	'	,	'	E	'	,	'	The learner is not over the school leaving age	'	)	,
	(	'	Ethnicity_01	'	,	'	E	'	,	'	This Ethnicity is not a valid code	'	)	,
	(	'	Sex_01	'	,	'	E	'	,	'	This Sex is not a valid code	'	)	,
	(	'	LLDDHealthProb_01	'	,	'	E	'	,	'	This LLDD and health problem is not a valid code	'	)	,
	(	'	LLDDHealthProb_04	'	,	'	E	'	,	'	The LLDD and Health Problem record has been returned and the learner does not consider himself or herself to have a learning difficulty and/or disability or health problem	'	)	,
	(	'	LLDDHealthProb_06	'	,	'	E	'	,	'	The LLDD and Health Problem record has not been returned and the learner does consider himself or herself to have a learning difficulty and/or disability or health problem	'	)	,
	(	'	LLDDHealthProb_07	'	,	'	E	'	,	'	The LLDD and Health Problem record has not been returned and the learner does consider himself or herself to have a learning difficulty and/or disability or health problem	'	)	,
	(	'	NINumber_01	'	,	'	E	'	,	'	This National Insurance number is not in the correct format	'	)	,
	(	'	NINumber_02	'	,	'	E	'	,	'	The National Insurance number must be returned for this learner	'	)	,
	(	'	PriorAttain_01	'	,	'	E	'	,	'	The Prior attainment has not been returned	'	)	,
	(	'	PriorAttain_02	'	,	'	W	'	,	'	This Prior attainment is not valid if the learning aim is a full level 2 or full level 3	'	)	,
	(	'	PriorAttain_03	'	,	'	E	'	,	'	This Prior attainment is not a valid code	'	)	,
	(	'	PriorAttain_04	'	,	'	E	'	,	'	The Prior attainment is not valid if the programme is a funded intermediate or advanced level apprenticeship	'	)	,
	(	'	PriorAttain_05	'	,	'	E	'	,	'	The prior attainment is level 4 or above and the learner is on a higher level 4 apprenticeship	'	)	,
	(	'	PriorAttain_06	'	,	'	E	'	,	'	The Learners prior attainment does not match the prior attainment described in the ESF Tender Specification	'	)	,
	(	'	PriorAttain_07	'	,	'	E	'	,	'	The Prior attainment is not valid for a traineeship programme	'	)	,
	(	'	Accom_01	'	,	'	E	'	,	'	This Accommodation is not a valid code	'	)	,
	(	'	ALSCost_02	'	,	'	E	'	,	'	The Learning support cost field must only be returned for High Needs Students	'	)	,
	(	'	PlanLearnHours_01	'	,	'	E	'	,	'	The Planned learning hours have not been returned	'	)	,
	(	'	PlanLearnHours_02	'	,	'	W	'	,	'	The Planned learning hours are zero	'	)	,
	(	'	PlanLearnHours_03	'	,	'	E	'	,	'	The sum of the Planned learning hours and the Planned employability, enrichment and pastoral hours is zero	'	)	,
	(	'	PlanLearnHours_04	'	,	'	W	'	,	'	The sum of the Planned learning hours and the Planned employability, enrichment and pastoral hours is greater than 1,000 hours 	'	)	,
	(	'	PlanLearnHours_05	'	,	'	E	'	,	'	The sum of the Planned learning hours and the Planned employability, enrichment and pastoral hours is greater than 4,000 hours 	'	)	,
	(	'	PlanEEPHours_01	'	,	'	E	'	,	'	The Planned employability, enrichment and pastoral hours have not been returned	'	)	,
	(	'	MathGrade_01	'	,	'	E	'	,	'	The GCSE maths qualification grade has not been returned	'	)	,
	(	'	MathGrade_02	'	,	'	E	'	,	'	The GCSE maths qualification grade is not a valid code	'	)	,
	(	'	MathGrade_03	'	,	'	E	'	,	'	The Learner FAM Type of Eligibility for EFA disadvantage funding must be returned	'	)	,
	(	'	MathGrade_04	'	,	'	E	'	,	'	GCSE maths qualification grade must be NONE	'	)	,
	(	'	EngGrade_01	'	,	'	E	'	,	'	The GCSE English qualification grade has not been returned	'	)	,
	(	'	EngGrade_02	'	,	'	E	'	,	'	The GCSE English qualification grade is not a valid code	'	)	,
	(	'	EngGrade_03	'	,	'	E	'	,	'	The Learner FAM Type of Eligibility for EFA disadvantage funding must be returned	'	)	,
	(	'	EngGrade_04	'	,	'	E	'	,	'	GCSE English qualification grade must be NONE	'	)	,
	(	'	PostcodePrior_01	'	,	'	W	'	,	'	The Postcode prior to enrolment is not valid	'	)	,
	(	'	PostcodePrior_02	'	,	'	E	'	,	'	The Postcode prior to enrolment is not in the correct format	'	)	,
	(	'	Postcode_14	'	,	'	W	'	,	'	The Postcode is not valid	'	)	,
	(	'	Postcode_15	'	,	'	E	'	,	'	The Postcode is not in the correct format	'	)	,
	(	'	Addline1_03	'	,	'	E	'	,	'	Address line 1 has not been returned.	'	)	,
	(	'	ContPrefType_01	'	,	'	E	'	,	'	This Contact preference type and code is not valid	'	)	,
	(	'	ContPrefType_02	'	,	'	E	'	,	'	The combination of Contact preference type and code is not valid, this learner is not to be contacted	'	)	,
	(	'	ContPrefType_03	'	,	'	E	'	,	'	This Contact preference type and code is not valid for this Learning start date	'	)	,
	(	'	LLDDCat_01	'	,	'	E	'	,	'	The LLDD and health problem category is not a valid code	'	)	,
	(	'	LLDDCat_02	'	,	'	E	'	,	'	This LLDD and health problem category is not valid for this start date	'	)	,
	(	'	PrimaryLLDD_01	'	,	'	E	'	,	'	The Primary LLDD and health problem is not recorded on one of the LLDD and health problem records	'	)	,
	(	'	PrimaryLLDD_02	'	,	'	E	'	,	'	The Primary LLDD and health problem is not a valid code	'	)	,
	(	'	PrimaryLLDD_03	'	,	'	E	'	,	'	There must only be one Primary LLDD and Health problem record	'	)	,
	(	'	PrimaryLLDD_04	'	,	'	E	'	,	'	The Primary LLDD and health problem is not recorded	'	)	,
	(	'	LearnFAMType_01	'	,	'	E	'	,	'	This FAM type and code is not valid	'	)	,
	(	'	LearnFAMType_03	'	,	'	E	'	,	'	This FAM type and code is not valid for this Learning start date 	'	)	,
	(	'	LearnFAMType_09	'	,	'	E	'	,	'	There must not be more than one record with a FAM type of LDA, HNS, EHC, DLA, SEN, MCF, ECF or FME	'	)	,
	(	'	LearnFAMType_10	'	,	'	E	'	,	'	There must not be more than four records with a FAM type of LSR	'	)	,
	(	'	LearnFAMType_11	'	,	'	E	'	,	'	There must not be more than two records with a FAM type of EDF, NLM or PPE	'	)	,
	(	'	LearnFAMType_14	'	,	'	E	'	,	'	The learner must not have both a FAM type of SEN and (LDA or EHC)	'	)	,
	(	'	LearnFAMType_15	'	,	'	E	'	,	'	The learner is recorded as exempt from maths GCSE condition of funding due to a learning difficulty but there is no Learning difficulty assessment or Education health care plan recorded	'	)	,
	(	'	LearnFAMType_16	'	,	'	E	'	,	'	The learner is recorded as exempt from English GCSE condition of funding due to a learning difficulty but there is no Learning difficulty assessment or Education health care plan recorded	'	)	,
	(	'	ProvSpecLearnMonOccur_01	'	,	'	E	'	,	'	This Provider specified learner monitoring occurrence is not A or B	'	)	,
	(	'	EmpStat_01	'	,	'	E	'	,	'	An Employment status record has not been returned that applies prior to this Learning start date 	'	)	,
	(	'	EmpStat_02	'	,	'	E	'	,	'	An Employment status record has not been returned that applies prior to this Learning start date 	'	)	,
	(	'	EmpStat_04	'	,	'	E	'	,	'	This Employment status is not valid for learning aims funded by ESF	'	)	,
	(	'	EmpStat_05	'	,	'	E	'	,	'	This Employment status is not a valid code	'	)	,
	(	'	EmpStat_06	'	,	'	E	'	,	'	An Employment status record has not been returned that applies prior to the Learning start date	'	)	,
	(	'	EmpStat_07	'	,	'	E	'	,	'	An Employment status record has not been returned	'	)	,
	(	'	EmpStat_08	'	,	'	E	'	,	'	An Employment status record has not been returned that applies prior to the Learning start date	'	)	,
	(	'	EmpStat_09	'	,	'	E	'	,	'	An Employment status record has not been returned that applies prior to the Learning start date 	'	)	,
	(	'	EmpStat_10	'	,	'	E	'	,	'	An Employment status record has not been returned that applies prior to the Learning start date 	'	)	,
	(	'	EmpStat_11	'	,	'	E	'	,	'	An Employment status record has not been returned that applies prior to the Learning start date 	'	)	,
	(	'	EmpStat_12	'	,	'	W	'	,	'	The Employment status on the start date of an apprenticeship programme should be employed	'	)	,
	(	'	EmpStat_14	'	,	'	E	'	,	'	The Learners Employment status does not match the employment status described in the ESF Tender Specification	'	)	,
	(	'	EmpStat_15	'	,	'	E	'	,	'	The Employment status on the start date of an apprenticeship programme must not be unknown	'	)	,
	(	'	EmpStat_17	'	,	'	E	'	,	'	The Employment status on the start date of an traineeship programme must not be unknown	'	)	,
	(	'	EmpStat_18	'	,	'	E	'	,	'	The learner must not be employed for more than 16 hours her week at the start of the programme	'	)	,
	(	'	DateEmpStatApp_01	'	,	'	E	'	,	'	The Date employment status applies must not be after the current teaching year	'	)	,
	(	'	DateEmpStatApp_02	'	,	'	E	'	,	'	The Date employment status applies must not be before 1 August 1990	'	)	,
	(	'	EmpId_01	'	,	'	E	'	,	'	The Employer identifier is not valid 	'	)	,
	(	'	EmpId_02	'	,	'	E	'	,	'	The Employer identifier does not pass the checksum calculation	'	)	,
	(	'	EmpId_10	'	,	'	E	'	,	'	The Employer identifier has not been returned	'	)	,
	(	'	EmpId_12	'	,	'	W	'	,	'	The Employer identifier is not valid	'	)	,
	(	'	EmpId_13	'	,	'	E	'	,	'	The Employer identifier is not valid	'	)	,
	(	'	ESMType_01	'	,	'	E	'	,	'	The Employment status monitoring type and code is not valid	'	)	,
	(	'	ESMType_02	'	,	'	E	'	,	'	The Learners Employment status is in paid employment and the Employment intensity indicator has not been returned	'	)	,
	(	'	ESMType_05	'	,	'	E	'	,	'	The Learners Employment status is in paid employment and the Length of unemployment has been returned	'	)	,
	(	'	ESMType_07	'	,	'	E	'	,	'	The learner is self employed and the Employment status is not in paid employment	'	)	,
	(	'	ESMType_08	'	,	'	E	'	,	'	The Length of unemployment has not been returned	'	)	,
	(	'	ESMType_09	'	,	'	E	'	,	'	The Length of employment has not been returned	'	)	,
	(	'	ESMType_10	'	,	'	E	'	,	'	The Length of employment has been returned	'	)	,
	(	'	ESMType_11	'	,	'	E	'	,	'	The Employment status monitoring type and code is not valid for the Employment status date	'	)	,
	(	'	ESMType_12	'	,	'	E	'	,	'	The Employment intensity indicator or Self employed indicator has been returned	'	)	,
	(	'	ESMType_13	'	,	'	E	'	,	'	The Learners length of unemployment does not match the length of unemployment described in the ESF Tender Specification	'	)	,
	(	'	ESMType_14	'	,	'	E	'	,	'	The Learners benefit status does not match the benefit status described in the ESF Tender Specification	'	)	,
	(	'	ESMType_15	'	,	'	E	'	,	'	There must not be more than one record with an ESM type of SEI, EII, LOU, LOE, BSI, PEI, or SEM	'	)	,
	(	'	LearnAimRef_01	'	,	'	E	'	,	'	This Learning aim reference is not a valid lookup on LARS	'	)	,
	(	'	LearnAimRef_03	'	,	'	E	'	,	'	This Learning aim reference is part of an Adult Skills funded apprenticeship and is not valid in the LARS database on this Learning start date	'	)	,
	(	'	LearnAimRef_05	'	,	'	E	'	,	'	This Learning aim reference is Adult Skills funded and is not valid in the LARS database on this Learning start date	'	)	,
	(	'	LearnAimRef_36	'	,	'	E	'	,	'	This Learning aim reference is not valid in the LARS database for this Funding model and this Learning start date 	'	)	,
	(	'	LearnAimRef_09	'	,	'	E	'	,	'	This Learning aim reference is not valid in the LARS database for this Funding model and this Learning start date	'	)	,
	(	'	LearnAimRef_10	'	,	'	E	'	,	'	This Learning aim reference is 16-19 EFA funded and is not valid in the LARS database on this Learning start date	'	)	,
	(	'	LearnAimRef_11	'	,	'	E	'	,	'	This Learning aim reference is Adult Skills funded and is not valid in the LARS database on this Learning start date	'	)	,
	(	'	LearnAimRef_12	'	,	'	E	'	,	'	This Learning aim reference is Community Learning funded and is not valid in the LARS database on this Learning start date	'	)	,
	(	'	LearnAimRef_37	'	,	'	E	'	,	'	This Learning aim reference is not valid in the LARS database for this Funding model and this Learning start date 	'	)	,
	(	'	LearnAimRef_42	'	,	'	E	'	,	'	This Learning aim reference is OLASS funded and is not valid in the LARS database on this Learning start date	'	)	,
	(	'	LearnAimRef_45	'	,	'	E	'	,	'	This Learning aim reference is financed by an Advanced Learner Loan and is not valid in the LARS database on this Learning start date	'	)	,
	(	'	LearnAimRef_46	'	,	'	E	'	,	'	This learner is recorded as in receipt of JSA, ESA (WRAG), another state benefit or Universal credit, is part of a Traineeship or recorded with LDM328 and this Learning aim reference is not valid in the LARS database on this Learning start date	'	)	,
	(	'	LearnAimRef_16	'	,	'	E	'	,	'	This Learning aim reference is not valid in the LARS database for this Funding Model for a new starter on this Learning start date	'	)	,
	(	'	LearnAimRef_17	'	,	'	E	'	,	'	This Learning aim reference is Adult Skills funded and is not valid in the LARS database for a new starter on this Learning start date	'	)	,
	(	'	LearnAimRef_18	'	,	'	E	'	,	'	This Learning aim reference is 16-19 EFA funded and is not valid in the LARS database for a new starter on this Learning start date 	'	)	,
	(	'	LearnAimRef_19	'	,	'	E	'	,	'	This Learning aim reference is Community Learning funded and is not valid in the LARS database for a new starter on this Learning start date	'	)	,
	(	'	LearnAimRef_38	'	,	'	E	'	,	'	This Learning aim reference is not valid in the LARS database for this Funding model for a new starter on this Learning start date 	'	)	,
	(	'	LearnAimRef_43	'	,	'	E	'	,	'	This Learning aim reference is OLASS funded and is not valid in the LARS database for a new starter on this Learning start date 	'	)	,
	(	'	LearnAimRef_47	'	,	'	E	'	,	'	This Learning aim reference is financed by an Advanced Learner Loan and is not valid in the LARS database for a new starter on this Learning start date 	'	)	,
	(	'	LearnAimRef_48	'	,	'	E	'	,	'	This learner is recorded as in receipt of JSA, ESA (WRAG), another state benefit or Universal credit, is part of a traineeship or recorded with LDM328 and this Learning aim reference is not valid in the LARS database for a new starter on this Learning start date 	'	)	,
	(	'	LearnAimRef_23	'	,	'	E	'	,	'	The Learning aim reference is valid in the LARS database for this Funding modeal for this teaching year	'	)	,
	(	'	LearnAimRef_24	'	,	'	E	'	,	'	This Learning aim reference is 16-19 EFA funded and is not valid in the LARS database for this teaching year	'	)	,
	(	'	LearnAimRef_25	'	,	'	E	'	,	'	This Learning aim reference is Adult Skills funded and is not valid in the LARS database for this teaching year	'	)	,
	(	'	LearnAimRef_26	'	,	'	E	'	,	'	This Learning aim reference is Community Learning funded and is not valid in the LARS database for this teaching year	'	)	,
	(	'	LearnAimRef_39	'	,	'	E	'	,	'	This Learning aim reference is not valid in the LARS database for this Funding model for this teaching year	'	)	,
	(	'	LearnAimRef_44	'	,	'	E	'	,	'	This Learning aim reference is OLASS funded and is not valid in the LARS database for this teaching year	'	)	,
	(	'	LearnAimRef_49	'	,	'	E	'	,	'	This Learning aim reference is financed by an Advanced Learner Loan and is not valid in the LARS database for this teaching year	'	)	,
	(	'	LearnAimRef_50	'	,	'	E	'	,	'	This learner is recorded as in receipt of JSA, ESA (WRAG), another state benefit or Universal credit, or recorded with LDM328 and this Learning aim reference is not valid in the LARS database for this teaching year	'	)	,
	(	'	LearnAimRef_53	'	,	'	E	'	,	'	This Learning aim reference is not valid in the LARS database for this Funding model for this teaching year	'	)	,
	(	'	LearnAimRef_54	'	,	'	E	'	,	'	This Learning aim reference is not valid in the LARS database for this Funding model for this teaching year	'	)	,
	(	'	LearnAimRef_29	'	,	'	E	'	,	'	This Learning aim reference is not valid for this Funding model 	'	)	,
	(	'	LearnAimRef_30	'	,	'	E	'	,	'	This Learning aim reference is not valid for a programme aim	'	)	,
	(	'	LearnAimRef_40	'	,	'	E	'	,	'	This Learning aim reference is not valid for an aim which is not a programme aim	'	)	,
	(	'	LearnAimRef_52	'	,	'	E	'	,	'	This Learning aim reference is not valid where the learning aim is not part of a traineeship	'	)	,
	(	'	LearnAimRef_55	'	,	'	E	'	,	'	This learning aim is not recorded as the Core aim	'	)	,
	(	'	LearnAimRef_56	'	,	'	E	'	,	'	This learning aim is not valid for Adult Skills funding	'	)	,
	(	'	LearnAimRef_57	'	,	'	E	'	,	'	This learning aim is not valid for Adult Skills funding	'	)	,
	(	'	LearnAimRef_59	'	,	'	E	'	,	'	This learning aim is not valid for Adult Skills funding	'	)	,
	(	'	LearnAimRef_60	'	,	'	E	'	,	'	The learning aim must be Adult skills or ESF funded	'	)	,
	(	'	LearnAimRef_61	'	,	'	E	'	,	'	The learning aim must be Adult skills or ESF funded	'	)	,
	(	'	LearnAimRef_62	'	,	'	E	'	,	'	The learning aim must be Adult skills or Other SFA funded	'	)	,
	(	'	LearnAimRef_63	'	,	'	E	'	,	'	The learning aim is not Community Learning or Local Authority Community Learning funded	'	)	,
	(	'	LearnAimRef_64	'	,	'	E	'	,	'	The learning aim must be Non-funded	'	)	,
	(	'	LearnAimRef_65	'	,	'	E	'	,	'	The learning aim must be Non-funded	'	)	,
	(	'	LearnAimRef_66	'	,	'	E	'	,	'	The learning aim must Adult skills or Other SFA funded	'	)	,
	(	'	LearnAimRef_67	'	,	'	E	'	,	'	This Learning aim reference is not valid in the LARS database for this Funding model and this Learning start date 	'	)	,
	(	'	LearnAimRef_68	'	,	'	E	'	,	'	This Learning aim reference is not valid in the LARS database for this Funding model and this Learning start date 	'	)	,
	(	'	LearnAimRef_69	'	,	'	E	'	,	'	This Learning aim reference is not valid in the LARS database for this Funding model for a new starter on this Learning start date 	'	)	,
	(	'	LearnAimRef_70	'	,	'	E	'	,	'	This Learning aim reference is not valid in the LARS database for this Funding model for this teaching year	'	)	,
	(	'	LearnAimRef_71	'	,	'	E	'	,	'	The learning aims sector subject area does not match the ESF Tender Specification.	'	)	,
	(	'	LearnAimRef_72	'	,	'	E	'	,	'	The learning aims level does not match the level described in the ESF Tender Specification.	'	)	,
	(	'	LearnAimRef_73	'	,	'	E	'	,	'	The learning aims sector subject area and level does not match the ESF Tender Specification.	'	)	,
	(	'	LearnAimRef_74	'	,	'	E	'	,	'	This Learning aim reference is Adult skills funded and is not valid in the LARS database on this Learning start date	'	)	,
	(	'	LearnAimRef_75	'	,	'	E	'	,	'	This Learning aim reference is Adult skills funded and is not valid in the LARS database on this Learning start date	'	)	,
	(	'	LearnAimRef_76	'	,	'	E	'	,	'	This Learning aim reference is Adult skills funded and is not valid in the LARS database for a new starter on this Learning start date	'	)	,
	(	'	LearnAimRef_77	'	,	'	E	'	,	'	This Learning aim reference is Adult skills funded and is not valid in the LARS database for this teaching year	'	)	,
	(	'	LearnAimRef_78	'	,	'	E	'	,	'	This learning aim is not valid for Adult skills funding	'	)	,
	(	'	LearnAimRef_79	'	,	'	E	'	,	'	This learning aim is not valid for Adult skills funding	'	)	,
	(	'	LearnAimRef_80	'	,	'	E	'	,	'	This learning aim is not valid for Adult skills funding	'	)	,
	(	'	LearnAimRef_81	'	,	'	E	'	,	'	The learning aim is not valid for Adult skills funding	'	)	,
	(	'	AimType_01	'	,	'	E	'	,	'	This Aim type is not a valid code	'	)	,
	(	'	AimType_05	'	,	'	E	'	,	'	This Aim type is not valid for this Funding model 	'	)	,
	(	'	AimType_06	'	,	'	W	'	,	'	The Core aim is in the following teaching year	'	)	,
	(	'	AimType_07	'	,	'	E	'	,	'	A core aim must not be recorded with a source of funding of 105	'	)	,
	(	'	AimSeqNumber_02	'	,	'	E	'	,	'	The Aim sequence number is greater than the count of the learning aims	'	)	,
	(	'	LearnStartDate_02	'	,	'	E	'	,	'	The Learning start date is more than 10 years before the start of the current teaching year	'	)	,
	(	'	LearnStartDate_03	'	,	'	E	'	,	'	The Learning start date must not be after the end of the current teaching year	'	)	,
	(	'	LearnStartDate_05	'	,	'	E	'	,	'	The Learning start date must not be on or before the Learners Date of birth	'	)	,
	(	'	LearnStartDate_06	'	,	'	E	'	,	'	The Learning start date of the apprenticeship programme must not be after the Effective to date of this apprenticeship pathway	'	)	,
	(	'	LearnStartDate_07	'	,	'	E	'	,	'	The Learning start date of the apprenticeship programme must not be after the Effective to date of this component aim for this apprenticeship pathway	'	)	,
	(	'	LearnStartDate_12	'	,	'	E	'	,	'	The Learning start date must not be more than one year in the future	'	)	,
	(	'	LearnStartDate_13	'	,	'	E	'	,	'	The Learning start date of the apprenticeship standard programme must not be after the Effective to date of this apprenticeship standard	'	)	,
	(	'	LearnStartDate_14	'	,	'	E	'	,	'	The Learning start date of the apprenticeship standard programme must not be after the Effective to date of this component aim for this standard	'	)	,
	(	'	LearnStartDate_15	'	,	'	E	'	,	'	The Learning start date must be after the start date of the completed ZESF0001 aim for that contract	'	)	,
	(	'	LearnStartDate_16	'	,	'	E	'	,	'	The Learning start date must not be before the start date of the contract	'	)	,
	(	'	OrigLearnStartDate_01	'	,	'	E	'	,	'	The Original learning start date must not be more than 10 years before the Learning start date 	'	)	,
	(	'	OrigLearnStartDate_02	'	,	'	E	'	,	'	The Original learning start date must not be on or after the Learning start date	'	)	,
	(	'	OrigLearnStartDate_03	'	,	'	E	'	,	'	The Original learning start date must not be returned	'	)	,
	(	'	OrigLearnStartDate_04	'	,	'	E	'	,	'	The Restart indicator has not been returned	'	)	,
	(	'	OrigLearnStartDate_05	'	,	'	E	'	,	'	This Learning aim reference is not valid in the LARS database for this Funding model on this Original learning start date 	'	)	,
	(	'	OrigLearnStartDate_06	'	,	'	E	'	,	'	This Learning aim reference is Adult Skills funded and is not valid in the LARS database on this Original learning start date 	'	)	,
	(	'	OrigLearnStartDate_07	'	,	'	E	'	,	'	This Learning aim reference is not valid in the LARS database for this Funding model on this Original learning start date	'	)	,
	(	'	OrigLearnStartDate_08	'	,	'	E	'	,	'	This Learning aim reference is financed by an Advanced Learner Loan and is not valid in the LARS database on this Original learning start date 	'	)	,
	(	'	OrigLearnStartDate_09	'	,	'	E	'	,	'	The Original learning start date for this funding model must not be before 1 May 2017	'	)	,
	(	'	LearnPlanEndDate_02	'	,	'	E	'	,	'	The Learning planned end date must not be before the Learning start date	'	)	,
	(	'	LearnPlanEndDate_03	'	,	'	E	'	,	'	The Learning planned end date must not be 10 years or more after the Learning start date 	'	)	,
	(	'	LearnPlanEndDate_04	'	,	'	W	'	,	'	The Learning planned end date should not be 5 years or more after the end of the current teaching year 	'	)	,
	(	'	FundModel_01	'	,	'	E	'	,	'	This Funding model is not a valid code	'	)	,
	(	'	FundModel_03	'	,	'	E	'	,	'	This Funding model is not valid for a learning aim financed by an Advanced Learner Loan	'	)	,
	(	'	FundModel_04	'	,	'	E	'	,	'	This Funding model is not valid for a learning aim which is part of an apprenticeship programme.	'	)	,
	(	'	FundModel_05	'	,	'	E	'	,	'	This Funding model is not valid for starts before 1 May 2017	'	)	,
	(	'	FundModel_06	'	,	'	E	'	,	'	The funding model is not valid for this aim	'	)	,
	(	'	FundModel_07	'	,	'	E	'	,	'	The funding model is not valid for an apprenticeship programme	'	)	,
	(	'	FundModel_08	'	,	'	E	'	,	'	The funding model is not valid for this apprenticeship programme	'	)	,
	(	'	FundModel_09	'	,	'	E	'	,	'	The funding model is not valid for this apprenticeship programme	'	)	,
	(	'	ProgType_01	'	,	'	E	'	,	'	The Programme type must be returned for this learning aim	'	)	,
	(	'	ProgType_02	'	,	'	E	'	,	'	The Programme type must not be returned for this Aim type	'	)	,
	(	'	ProgType_03	'	,	'	E	'	,	'	This Programme type is not a valid code	'	)	,
	(	'	ProgType_04	'	,	'	E	'	,	'	This Programme type is not a valid code for this Learning start date 	'	)	,
	(	'	ProgType_06	'	,	'	E	'	,	'	This Programme type is not a valid code for this Funding model	'	)	,
	(	'	ProgType_07	'	,	'	E	'	,	'	The planned duration for the programme exceeds the maximum allowed duration for a traineeship	'	)	,
	(	'	ProgType_08	'	,	'	E	'	,	'	The actual duration of the programme exceeds the maximum allowed duration for a traineeship	'	)	,
	(	'	ProgType_09	'	,	'	E	'	,	'	This learning aim is not valid for this level of apprenticeship	'	)	,
	(	'	ProgType_10	'	,	'	E	'	,	'	This learning aim is not valid for this level of apprenticeship	'	)	,
	(	'	ProgType_12	'	,	'	W	'	,	'	This learning aim is not valid for the Framework	'	)	,
	(	'	ProgType_13	'	,	'	E	'	,	'	The current duration of the programme exceeds the maximum allowed duration for a traineeship	'	)	,
	(	'	FworkCode_01	'	,	'	E	'	,	'	The Framework code must be returned	'	)	,
	(	'	FworkCode_02	'	,	'	E	'	,	'	The Framework code must not be returned	'	)	,
	(	'	FworkCode_05	'	,	'	E	'	,	'	This Framework code, Pathway code and Programme type combination is not valid in the LARS database for this Learning aim reference	'	)	,
	(	'	PwayCode_01	'	,	'	E	'	,	'	This Apprenticeship pathway code is not a valid code in the LARS database	'	)	,
	(	'	PwayCode_02	'	,	'	E	'	,	'	The Apprenticeship pathway code has been returned, it is not required for non-apprenticeship learning aims and apprenticeship standards	'	)	,
	(	'	PwayCode_03	'	,	'	E	'	,	'	The Apprenticeship pathway code has not been returned	'	)	,
	(	'	StdCode_01	'	,	'	E	'	,	'	An apprenticeship standard code has not been returned. 	'	)	,
	(	'	StdCode_02	'	,	'	E	'	,	'	The apprenticeship standard code is not valid.	'	)	,
	(	'	StdCode_03	'	,	'	E	'	,	'	The Apprenticeship standard code must not be returned	'	)	,
	(	'	PartnerUKPRN_01	'	,	'	E	'	,	'	This Subcontracted or partnership UKPRN is not valid	'	)	,
	(	'	PartnerUKPRN_02	'	,	'	E	'	,	'	The Subcontracted or partnership UKPRN must not be on programme aims	'	)	,
	(	'	PartnerUKPRN_03	'	,	'	E	'	,	'	The Subcontracted or partnership UKPRN must not be the same as the Learning provider UKPRN	'	)	,
	(	'	DelLocPostCode_03	'	,	'	W	'	,	'	This Delivery location postcode is not valid 	'	)	,
	(	'	DelLocPostCode_11	'	,	'	E	'	,	'	The Delivery location postcode is not in the correct format	'	)	,
	(	'	DelLocPostCode_14	'	,	'	E	'	,	'	The Delivery location postcode is not valid in the local authority described in the ESF Tender Specification	'	)	,
	(	'	DelLocPostCode_15	'	,	'	E	'	,	'	The Delivery location postcode is not valid in the LEP described in the ESF Tender Specification	'	)	,
	(	'	DelLocPostCode_16	'	,	'	E	'	,	'	This Delivery location postcode is not valid 	'	)	,
	(	'	AddHours_01	'	,	'	E	'	,	'	The Additional delivery hours must not be returned for learning aims that started prior to 1 August 2015	'	)	,
	(	'	AddHours_02	'	,	'	E	'	,	'	The Additional delivery hours must not be returned for EFA, Community Learning or Non-funded provision	'	)	,
	(	'	AddHours_03	'	,	'	E	'	,	'	The Additional delivery hours must only be returned for ESOL qualification or unit aims	'	)	,
	(	'	AddHours_04	'	,	'	E	'	,	'	The Additional delivery hours must not exceed 24 hours in a day	'	)	,
	(	'	AddHours_05	'	,	'	W	'	,	'	The Additional delivery hours should not exceed 35 hours in a week	'	)	,
	(	'	AddHours_06	'	,	'	W	'	,	'	The Additional delivery hours divided by the number of days of study is greater than 9 and less than 24	'	)	,
	(	'	PriorLearnFundAdj_01	'	,	'	E	'	,	'	The Funding adjustment for prior learning must not be returned	'	)	,
	(	'	PriorLearnFundAdj_02	'	,	'	W	'	,	'	The Funding adjustment for prior learning should be completed when the Restart indicator is returned	'	)	,
	(	'	PriorLearnFundAdj_03	'	,	'	W	'	,	'	The Funding adjustment for prior learning field should be completed for this learning aim	'	)	,
	(	'	OtherFundAdj_01	'	,	'	E	'	,	'	The Other funding adjustment must not be returned for this Funding model	'	)	,
	(	'	ConRefNumber_01	'	,	'	E	'	,	'	The Contract reference number is not valid	'	)	,
	(	'	ConRefNumber_02	'	,	'	E	'	,	'	The Contract reference number must be returned for ESF funded aims	'	)	,
	(	'	ConRefNumber_03	'	,	'	E	'	,	'	The Contract reference number must not be returned for this Funding model	'	)	,
	(	'	EPAOrgID_02	'	,	'	E	'	,	'	The End point assessment organisation payment record has been returned but there is no record of the End point assessment organisation.	'	)	,
	(	'	EPAOrgID_03	'	,	'	E	'	,	'	The End point assessment organisation has been returned but there is no record of the associated financial record.	'	)	,
	(	'	EmpOutcome_01	'	,	'	E	'	,	'	The Employment outcome must not be returned for this Funding model	'	)	,
	(	'	EmpOutcome_02	'	,	'	E	'	,	'	This Employment outcome is not a valid code	'	)	,
	(	'	EmpOutcome_03	'	,	'	E	'	,	'	The Employment outcome must not be returned for apprenticeships	'	)	,
	(	'	EmpOutcome_04	'	,	'	W	'	,	'	The Employment outcome should not be returned where there is no Benefit status indicator	'	)	,
	(	'	CompStatus_01	'	,	'	E	'	,	'	This Completion status is not a valid code	'	)	,
	(	'	CompStatus_02	'	,	'	E	'	,	'	The Learning actual end date must not be returned for this Completion status	'	)	,
	(	'	CompStatus_03	'	,	'	E	'	,	'	The Learning actual end date must be returned for this Completion status	'	)	,
	(	'	CompStatus_04	'	,	'	E	'	,	'	The Outcome must be returned for this completion status	'	)	,
	(	'	CompStatus_05	'	,	'	E	'	,	'	The Completion status is not valid for this Outcome	'	)	,
	(	'	CompStatus_06	'	,	'	E	'	,	'	The Completion status is not valid for this Outcome	'	)	,
	(	'	LearnActEndDate_01	'	,	'	E	'	,	'	The Learning actual end date must be after the Learning start date 	'	)	,
	(	'	LearnActEndDate_02	'	,	'	W	'	,	'	The Learning actual end date should be before the end of the current teaching year	'	)	,
	(	'	LearnActEndDate_03	'	,	'	E	'	,	'	The Learning actual end date must be before the end of the following teaching year	'	)	,
	(	'	LearnActEndDate_04	'	,	'	E	'	,	'	The Learning actual end date must be before the file preparation date	'	)	,
	(	'	WithdrawReason_02	'	,	'	E	'	,	'	This Withdrawal reason is not a valid code	'	)	,
	(	'	WithdrawReason_03	'	,	'	E	'	,	'	The Withdrawal reason must be returned for this Completion status	'	)	,
	(	'	WithdrawReason_04	'	,	'	E	'	,	'	The Withdrawal reason must not be returned for this Completion status 	'	)	,
	(	'	WithdrawReason_05	'	,	'	E	'	,	'	The Withdrawal reason is only valid for OLASS - Offenders in custody	'	)	,
	(	'	Outcome_01	'	,	'	E	'	,	'	This Outcome is not a valid code	'	)	,
	(	'	Outcome_04	'	,	'	E	'	,	'	The Achievement date must not be returned for this Outcome	'	)	,
	(	'	Outcome_05	'	,	'	E	'	,	'	The Learning actual end date must be returned for this Outcome	'	)	,
	(	'	Outcome_07	'	,	'	E	'	,	'	There must be a Destination and progression record returned for this Outcome	'	)	,
	(	'	Outcome_08	'	,	'	E	'	,	'	There must be a Destination and progression record returned for this Outcome	'	)	,
	(	'	Outcome_09	'	,	'	E	'	,	'	The Completion status is not valid for this Outcome	'	)	,
	(	'	AchDate_02	'	,	'	W	'	,	'	The Achievement date should not be after the current teaching year end date	'	)	,
	(	'	AchDate_03	'	,	'	E	'	,	'	The Achievement date must not be before the Learning start date 	'	)	,
	(	'	AchDate_04	'	,	'	E	'	,	'	The Learning actual end date must be returned for this Achievement date	'	)	,
	(	'	AchDate_05	'	,	'	E	'	,	'	The Achievement date must be after the Learning actual end date	'	)	,
	(	'	AchDate_07	'	,	'	E	'	,	'	The Achievement date must be before the file preparation date	'	)	,
	(	'	AchDate_08	'	,	'	E	'	,	'	The Achievement date must be completed for apprenticeship standards and traineeship programmes with a status of achieved	'	)	,
	(	'	AchDate_09	'	,	'	E	'	,	'	The Achievement date must not be completed for aims that are not traineeship or apprenticeship standard programme aims	'	)	,
	(	'	AchDate_10	'	,	'	E	'	,	'	The Achievement date must not be more than 6 months after the Learning actual end date	'	)	,
	(	'	OutGrade_01	'	,	'	E	'	,	'	This Outcome grade is not a valid code	'	)	,
	(	'	OutGrade_03	'	,	'	W	'	,	'	This Outcome grade is not valid for this level of qualification 	'	)	,
	(	'	OutGrade_04	'	,	'	E	'	,	'	The Outcome grade must not be returned for this Outcome	'	)	,
	(	'	OutGrade_05	'	,	'	E	'	,	'	This Outcome grade is not valid for this Outcome 	'	)	,
	(	'	OutGrade_06	'	,	'	E	'	,	'	This Outcome grade is not valid for this Outcome	'	)	,
	(	'	OutGrade_07	'	,	'	E	'	,	'	This Outcome grade is not valid for this type of qualification	'	)	,
	(	'	SWSupAimId_01	'	,	'	W	'	,	'	This Software supplier aim identifier is not in the correct format	'	)	,
	(	'	LearnDelFAMType_01	'	,	'	E	'	,	'	The Source of funding must be returned	'	)	,
	(	'	LearnDelFAMType_02	'	,	'	E	'	,	'	The Full or co-funding indicator must be returned for this Funding model	'	)	,
	(	'	LearnDelFAMType_03	'	,	'	E	'	,	'	The Community Learning provision type must be returned for this Funding model	'	)	,
	(	'	LearnDelFAMType_04	'	,	'	E	'	,	'	This FAM type and code is not valid	'	)	,
	(	'	LearnDelFAMType_06	'	,	'	E	'	,	'	This FAM type and code is not valid for this Learning start date 	'	)	,
	(	'	LearnDelFAMType_07	'	,	'	E	'	,	'	The Source of funding is not valid for this Funding model	'	)	,
	(	'	LearnDelFAMType_08	'	,	'	E	'	,	'	The Source of funding is not valid for this Funding model	'	)	,
	(	'	LearnDelFAMType_09	'	,	'	E	'	,	'	The Source of funding is not valid for this Funding model	'	)	,
	(	'	LearnDelFAMType_14	'	,	'	E	'	,	'	The Eligibility for enhanced apprenticeship funding is only valid for apprenticeship aims	'	)	,
	(	'	LearnDelFAMType_15	'	,	'	E	'	,	'	This Learning delivery monitoring code must not be returned where the Learning actual end date is completed	'	)	,
	(	'	LearnDelFAMType_16	'	,	'	E	'	,	'	This Learning delivery monitoring code is not valid for this file preparation date	'	)	,
	(	'	LearnDelFAMType_18	'	,	'	E	'	,	'	There must not be more than one record with a FAM type of SOF, FFI,  EEF, RES, ADL, ASL, SPP, NSA, WPP, POD or FLN	'	)	,
	(	'	LearnDelFAMType_20	'	,	'	E	'	,	'	There must not be more than three occurrences with a FAM type of HEM 	'	)	,
	(	'	LearnDelFAMType_22	'	,	'	E	'	,	'	The Full or co-funding indicator must not be returned for this Funding model	'	)	,
	(	'	LearnDelFAMType_24	'	,	'	E	'	,	'	This FAM Type is not valid for this learning aim start date 	'	)	,
	(	'	LearnDelFAMType_27	'	,	'	E	'	,	'	The ASL provision type must not be returned for this Funding model	'	)	,
	(	'	LearnDelFAMType_30	'	,	'	E	'	,	'	The Learning Delivery HE record must be returned for this FAM type	'	)	,
	(	'	LearnDelFAMType_31	'	,	'	E	'	,	'	There must not be more than four occurrences for the FAM type LDM	'	)	,
	(	'	LearnDelFAMType_35	'	,	'	E	'	,	'	The Advanced Learner Loans indicator must not be returned for this Funding model	'	)	,
	(	'	LearnDelFAMType_36	'	,	'	E	'	,	'	The Advanced Learner Loans indicator must be completed where the Advanced Learner Loans Bursary funding indicator has been returned	'	)	,
	(	'	LearnDelFAMType_38	'	,	'	E	'	,	'	The Advanced Learner Loans Bursary fund indicator is not required for this Funding mode	'	)	,
	(	'	LearnDelFAMType_39	'	,	'	W	'	,	'	The FAM type LDM should be returned for this Funding model	'	)	,
	(	'	LearnDelFAMType_40	'	,	'	E	'	,	'	The Advanced Learner Loans indicator must not be returned for apprenticeships	'	)	,
	(	'	LearnDelFAMType_44	'	,	'	E	'	,	'	The Household situation must be returned for this Funding model	'	)	,
	(	'	LearnDelFAMType_45	'	,	'	E	'	,	'	There must not be more than two occurrences of Household Situation	'	)	,
	(	'	LearnDelFAMType_46	'	,	'	E	'	,	'	The Funding model must be Adult skills	'	)	,
	(	'	LearnDelFAMType_48	'	,	'	E	'	,	'	The combination of Household situation codes is not valid	'	)	,
	(	'	LearnDelFAMType_50	'	,	'	E	'	,	'	Learning Support Funding must not be returned for this Funding model	'	)	,
	(	'	LearnDelFAMType_53	'	,	'	E	'	,	'	These FAM types must not be used by grant funded providers	'	)	,
	(	'	LearnDelFAMType_54	'	,	'	E	'	,	'	The combination of EEF and FFI codes is not valid	'	)	,
	(	'	LearnDelFAMType_56	'	,	'	E	'	,	'	The Full funding indicator is not valid for this learning aim	'	)	,
	(	'	LearnDelFAMType_57	'	,	'	E	'	,	'	The Full funding indicator is not valid for this learning aim	'	)	,
	(	'	LearnDelFAMType_58	'	,	'	E	'	,	'	The Full funding indicator is not valid for this learning aim	'	)	,
	(	'	LearnDelFAMType_59	'	,	'	E	'	,	'	The Full funding indicator is not valid for this learning aim	'	)	,
	(	'	LearnDelFAMType_60	'	,	'	E	'	,	'	The Full funding indicator is not valid for this learning aim	'	)	,
	(	'	LearnDelFAMType_63	'	,	'	E	'	,	'	The Apprenticeship contract type is only apprenticeship funded aims	'	)	,
	(	'	LearnDelFAMType_64	'	,	'	E	'	,	'	The Apprenticeship contract type must be returned for this learning aim	'	)	,
	(	'	LearnDelFAMDateFrom_01	'	,	'	W	'	,	'	The Date applies to must not be before the Date applies from for this FAM type	'	)	,
	(	'	LearnDelFAMDateFrom_02	'	,	'	E	'	,	'	The Date applies to should not be after the Learning planned end date 	'	)	,
	(	'	LearnDelFAMDateFrom_03	'	,	'	E	'	,	'	The Date applies to must not be after the Learning actual end date 	'	)	,
	(	'	LearnDelFAMDateTo_01	'	,	'	E	'	,	'	The Date applies to is before the Date applies from for this FAM type and code 	'	)	,
	(	'	LearnDelFAMDateTo_02	'	,	'	W	'	,	'	The Date applies to for this FAM type and code is after the Learning planned end date 	'	)	,
	(	'	LearnDelFAMDateTo_03	'	,	'	E	'	,	'	The Date applies to for this FAM type and code is after the Learning actual end date 	'	)	,
	(	'	LearnDelFAMDateTo_04	'	,	'	E	'	,	'	The Date applies to must not be returned for this FAM type	'	)	,
	(	'	WorkPlaceStartDate_01	'	,	'	E	'	,	'	The Work Placement record must be returned for this learning aim	'	)	,
	(	'	WorkPlaceStartDate_02	'	,	'	E	'	,	'	The Work placement start date must be after the Learning start date	'	)	,
	(	'	WorkPlaceStartDate_03	'	,	'	E	'	,	'	A Work placement record must not be returned for this learning aim	'	)	,
	(	'	WorkPlaceEndDate_01	'	,	'	E	'	,	'	The Work placement end date must be after the Work placement start date	'	)	,
	(	'	WorkPlaceEndDate_02	'	,	'	E	'	,	'	The Work placement end date must be before the Learning actual end date	'	)	,
	(	'	WorkPlaceMode_01	'	,	'	E	'	,	'	The Work placement mode must be a valid code	'	)	,
	(	'	WorkPlaceEmpId_01	'	,	'	E	'	,	'	The Work placement employer identifier is not valid	'	)	,
	(	'	WorkPlaceEmpId_02	'	,	'	E	'	,	'	The Work placement employer identifier does not pass the checksum calculation	'	)	,
	(	'	WorkPlaceEmpId_03	'	,	'	W	'	,	'	The Work placement employer identifier should not be used	'	)	,
	(	'	WorkPlaceEmpId_04	'	,	'	E	'	,	'	The Work placement employer identifier must not be used	'	)	,
	(	'	WorkPlaceEmpId_05	'	,	'	E	'	,	'	The Work placement employer identifier must be returned	'	)	,
	(	'	AFinType_01	'	,	'	E	'	,	'	A Apprenticeship Financial Record for the Total training price must be returned	'	)	,
	(	'	AFinType_02	'	,	'	E	'	,	'	The financial type and code is not valid	'	)	,
	(	'	AFinType_04	'	,	'	E	'	,	'	The Trailblazer Apprenticeship Financial Record must not be returned for this learning aim	'	)	,
	(	'	AFinType_05	'	,	'	E	'	,	'	There must not be more than ten occurrences of AFinType TNP	'	)	,
	(	'	AFinType_06	'	,	'	E	'	,	'	There must not be consecutive TNP records with the same Type and Amount	'	)	,
	(	'	AFinType_07	'	,	'	E	'	,	'	A financial record for the total assessment price must be returned	'	)	,
	(	'	AFinType_08	'	,	'	E	'	,	'	This Financial code must not be used for this funding mode	'	)	,
	(	'	AFinType_09	'	,	'	E	'	,	'	The  Apprenticeship Financial Record must be returned for this learning aim	'	)	,
	(	'	AFinType_10	'	,	'	W	'	,	'	The end-point assessment price should be returned	'	)	,
	(	'	AFinType_11	'	,	'	E	'	,	'	This Financial code must not be used for apprenticeship frameworks	'	)	,
	(	'	AFinType_12	'	,	'	E	'	,	'	The price must be returned for this programme	'	)	,
	(	'	AFinType_13	'	,	'	E	'	,	'	There must be a price record that applies from the start of the programme	'	)	,
	(	'	AFinType_14	'	,	'	E	'	,	'	A financial record for the training price must be returned	'	)	,
	(	'	AFinDate_01	'	,	'	E	'	,	'	The apprenticeship financial record date must not be more than one year before the start of the apprenticeship programme	'	)	,
	(	'	AFinDate_02	'	,	'	E	'	,	'	The apprenticeship financial record date must not be more than two years after the Learning planned end date of the apprenticeship programme	'	)	,
	(	'	AFinDate_03	'	,	'	E	'	,	'	The apprenticeship financial record date must not be after the file preparation date	'	)	,
	(	'	AFinDate_04	'	,	'	E	'	,	'	The price must not be after the learning actual end date	'	)	,
	(	'	AFinDate_05	'	,	'	E	'	,	'	A total training price must not be returned after a residual training price has been recorded	'	)	,
	(	'	AFinDate_06	'	,	'	E	'	,	'	A total assessment price must not be returned after a residual assessment price has been recorded	'	)	,
	(	'	AFinDate_07	'	,	'	E	'	,	'	A total training price and residual training price record must not have the same financial date	'	)	,
	(	'	AFinDate_08	'	,	'	E	'	,	'	A total assessment price and residual assessment price record must not have the same financial date	'	)	,
	(	'	ProvSpecDelMonOccur_01	'	,	'	E	'	,	'	This Provider specified delivery monitoring occurrence is not A , B, C or D	'	)	,
	(	'	LearnerHE_02	'	,	'	E	'	,	'	A Learning Delivery HE record must be returned	'	)	,
	(	'	TTACCOM_01	'	,	'	E	'	,	'	This Term time accommodation is not a valid code	'	)	,
	(	'	TTACCOM_02	'	,	'	E	'	,	'	This Term time accommodation is not a valid code for this Learning start date 	'	)	,
	(	'	TTACCOM_04	'	,	'	E	'	,	'	The Term time accommodation must be returned for this learning aim	'	)	,
	(	'	FINTYPE_01	'	,	'	E	'	,	'	This Financial support type is not a valid code	'	)	,
	(	'	FINTYPE_02	'	,	'	E	'	,	'	There must not be more than one record with a Financial support type of Cash, Near cash, Accommodation discounts, or Other	'	)	,
	(	'	LearningDeliveryHE_02	'	,	'	E	'	,	'	A Learning Delivery HE record must be returned for this Source of funding	'	)	,
	(	'	LearningDeliveryHE_03	'	,	'	E	'	,	'	A Learning Delivery HE record must be returned for this learning aim	'	)	,
	(	'	LearningDeliveryHE_06	'	,	'	E	'	,	'	A Learning Delivery HE record must not be returned for this learning aim	'	)	,
	(	'	LearningDeliveryHE_07	'	,	'	E	'	,	'	A Learning Delivery HE record must be returned for this learning aim	'	)	,
	(	'	LearningDeliveryHE_08	'	,	'	E	'	,	'	A Learning Delivery HE record must be returned for this learning aim	'	)	,
	(	'	NUMHUS_01	'	,	'	E	'	,	'	The Student instance identifier must be returned for this learning aim	'	)	,
	(	'	SSN_02	'	,	'	E	'	,	'	The Student support number does not pass the checksum calculation	'	)	,
	(	'	QUALENT3_01	'	,	'	E	'	,	'	The Qualification on entry must be returned for this learning aim	'	)	,
	(	'	QUALENT3_02	'	,	'	E	'	,	'	The Qualification on entry is not a valid code	'	)	,
	(	'	QUALENT3_03	'	,	'	E	'	,	'	The Qualification on entry is not a valid code for this Learning start date	'	)	,
	(	'	SOC2000_02	'	,	'	E	'	,	'	The Occupation code must be returned for this learning aim	'	)	,
	(	'	SOC2000_03	'	,	'	E	'	,	'	The Occupation code is not a valid code	'	)	,
	(	'	SOC2000_04	'	,	'	E	'	,	'	This Occupation code is not a valid code	'	)	,
	(	'	SEC_01	'	,	'	E	'	,	'	This Socio-economic indicator is not a valid code	'	)	,
	(	'	SEC_02	'	,	'	E	'	,	'	The Socio-economic indicator must be returned for this learning aim	'	)	,
	(	'	UCASAPPID_01	'	,	'	E	'	,	'	The UCAS application code must be returned for this learning aim	'	)	,
	(	'	TYPEYR_01	'	,	'	E	'	,	'	This Type of instance year is not a valid code	'	)	,
	(	'	TYPEYR_02	'	,	'	E	'	,	'	The Type of instance year is not valid for this Completion of year of instance	'	)	,
	(	'	MODESTUD_01	'	,	'	E	'	,	'	This Mode of study is not a valid code 	'	)	,
	(	'	MODESTUD_03	'	,	'	E	'	,	'	The Mode of study is not valid for this Special fee indicator	'	)	,
	(	'	FUNDLEV_01	'	,	'	E	'	,	'	This Level applicable to Funding Council HEIFES is not a valid code	'	)	,
	(	'	FUNDLEV_02	'	,	'	W	'	,	'	The Level applicable to Funding Council HEIFES is not valid for this type of learning aim 	'	)	,
	(	'	FUNDLEV_03	'	,	'	W	'	,	'	The Level applicable to Funding Council HEIFES is not valid for this type of learning aim 	'	)	,
	(	'	FUNDCOMP_01	'	,	'	E	'	,	'	This Completion of year of instance is not valid	'	)	,
	(	'	STULOAD_04	'	,	'	E	'	,	'	The Student instance FTE must be returned for this learning aim	'	)	,
	(	'	MSTUFEE_01	'	,	'	E	'	,	'	The Major source of tuition fees is not valid 	'	)	,
	(	'	MSTUFEE_02	'	,	'	E	'	,	'	The Major source of tuition fees is not valid for this Learning start date 	'	)	,
	(	'	MSTUFEE_03	'	,	'	W	'	,	'	The Major source of tuition fees is not consistent with the Domicile	'	)	,
	(	'	MSTUFEE_04	'	,	'	W	'	,	'	The Major source of tuition fees is not consistent with the Domicile 	'	)	,
	(	'	MSTUFEE_05	'	,	'	W	'	,	'	The Major source of tuition fees is not consistent with the Domicile	'	)	,
	(	'	PCOLAB_01	'	,	'	E	'	,	'	The Percentage not taught by this institution must be returned for this learning aim	'	)	,
	(	'	PCFLDCS_01	'	,	'	E	'	,	'	The total of the three Percentage taught in LDCS subject fields must equal 100%	'	)	,
	(	'	PCFLDCS_02	'	,	'	E	'	,	'	The Percentage taught in first LDCS subject must be returned for this learning aim	'	)	,
	(	'	PCFLDCS_03	'	,	'	E	'	,	'	The Percentage taught in first LDCS subject must not be returned for this learning aim	'	)	,
	(	'	PCSLDCS_01	'	,	'	E	'	,	'	The Percentage taught in second LDCS subject must be returned for this learning aim	'	)	,
	(	'	PCSLDCS_02	'	,	'	E	'	,	'	The Percentage taught in second LDCS subject must not be returned for this learning aim	'	)	,
	(	'	PCTLDCS_01	'	,	'	E	'	,	'	The Percentage taught in third LDCS subject must be returned for this learning aim	'	)	,
	(	'	PCTLDCS_02	'	,	'	E	'	,	'	The Percentage taught in third LDCS subject must not be returned for this learning aim	'	)	,
	(	'	SPECFEE_01	'	,	'	E	'	,	'	This Special fee indicator is not valid	'	)	,
	(	'	SPECFEE_02	'	,	'	E	'	,	'	The Special fee indicator is not valid for this Mode of study	'	)	,
	(	'	NETFEE_01	'	,	'	E	'	,	'	The Net tuition fee must be returned for this learning aim	'	)	,
	(	'	NETFEE_02	'	,	'	W	'	,	'	The Net tuition fee should not be greater than £9000	'	)	,
	(	'	GROSSFEE_01	'	,	'	E	'	,	'	The Gross tuition fee must be returned for this learning aim	'	)	,
	(	'	GROSSFEE_02	'	,	'	E	'	,	'	The Gross tuition fee must be equal to or greater than the Net tuition fee	'	)	,
	(	'	GROSSFEE_03	'	,	'	E	'	,	'	The Gross tuition fee must not be greater than £25000	'	)	,
	(	'	DOMICILE_01	'	,	'	E	'	,	'	The Domicile must be returned for this learning aim	'	)	,
	(	'	DOMICILE_02	'	,	'	E	'	,	'	The Domicile is not a valid code	'	)	,
	(	'	ELQ_01	'	,	'	E	'	,	'	The ELQ must be returned for this learning aim	'	)	,
	(	'	ELQ_02	'	,	'	E	'	,	'	The ELQ is not a valid code	'	)	,
	(	'	HEPostCode_01	'	,	'	W	'	,	'	The HE centre location postcode should be a valid postcode on the list of complete UK postcodes table or be ZZ99 9ZZ	'	)	,
	(	'	HEPostCode_02	'	,	'	E	'	,	'	The Postcode must conform to the valid postcode format	'	)	,
	(	'	OutULN_01	'	,	'	E	'	,	'	This Unique learner number does not pass the checksum calculation	'	)	,
	(	'	OutULN_02	'	,	'	E	'	,	'	This Unique learner number is not valid	'	)	,
	(	'	OutType_01	'	,	'	E	'	,	'	This Outcome type and code is not valid	'	)	,
	(	'	OutType_02	'	,	'	E	'	,	'	There is more than one record with the same start date and an Outcome type of EMP, NPE, VOL, GAP, SDE, or OTH	'	)	,
	(	'	OutType_03	'	,	'	E	'	,	'	There must not be more than two records with the same start date and an Outcome type of EDU	'	)	,
	(	'	OutType_04	'	,	'	E	'	,	'	There must not be DPOutcome records of both In Paid Employment and Not in paid Employment with the same Outcome start date	'	)	,
	(	'	OutType_05	'	,	'	E	'	,	'	The Outcome start date must not be after the valid to date in the OutType Code table	'	)	,
	(	'	OutStartDate_01	'	,	'	E	'	,	'	The Outcome start date must not be more then 3 years before the start of the current teaching year	'	)	,
	(	'	OutStartDate_02	'	,	'	E	'	,	'	The Outcome start date must not be more than 1 year after the end of the current teaching year	'	)	,
	(	'	OutEndDate_01	'	,	'	E	'	,	'	The Outcome end date must not be before the Outcome start date	'	)	,
	(	'	OutCollDate_01	'	,	'	E	'	,	'	The Outcome collection date must not be after the file preparation date	'	)	,
	(	'	OutCollDate_02	'	,	'	E	'	,	'	The Outcome collection date must not be more than 3 years before the start of the current teaching year	'	)	,
	(	'	R06	'	,	'	E	'	,	'	There must not be more than one Learner record with the same Learner reference number	'	)	,
	(	'	R07	'	,	'	E	'	,	'	There must not be more than one Learning Delivery record with the same Learner reference number and Aim sequence number combination	'	)	,
	(	'	R20	'	,	'	E	'	,	'	The learner must not have more than one competency aim at the same time	'	)	,
	(	'	R29	'	,	'	E	'	,	'	All open aims that are part of a programme must have the same Framework code, Apprenticeship pathway and Standard code (if returned)	'	)	,
	(	'	R30	'	,	'	E	'	,	'	All aims that are part of a programme must have a corresponding programme aim with the same Programme type, Framework code and Apprenticeship pathway (if returned)	'	)	,
	(	'	R31	'	,	'	E	'	,	'	An open programme must have an associated learning aim with the same Programme type, Framework code, Apprenticeship pathway and Standard code (if returned)	'	)	,
	(	'	R43	'	,	'	E	'	,	'	The learner must not have more than one Learner Employment status record with the same Date employment status applies	'	)	,
	(	'	R45	'	,	'	E	'	,	'	The learner must not have more than one LLDD and Health Problem record with the same LLDD and health problem category	'	)	,
	(	'	R47	'	,	'	E	'	,	'	The learner must not have more than one Learner Contact Preference record with the same Contact preference type and Contact preference code	'	)	,
	(	'	R49	'	,	'	E	'	,	'	The learner must not have more than one Learner Provider Specified Monitoring record with the same occurrence code	'	)	,
	(	'	R50	'	,	'	E	'	,	'	The learning aim must not have more than one Learning Delivery Provider Specified Monitoring record with the same occurrence code	'	)	,
	(	'	R51	'	,	'	E	'	,	'	The learner must not have more than one Learner Funding and Monitoring record with the same FAM type and code	'	)	,
	(	'	R52	'	,	'	E	'	,	'	The learner must not have more than one Learner Funding and Monitoring record with the same FAM type and code	'	)	,
	(	'	R56	'	,	'	E	'	,	'	The learner must not have more than one Learner Funding and Monitoring record with the same FAM type and code	'	)	,
	(	'	R58	'	,	'	E	'	,	'	The learner must not have more than one Learner Funding and Monitoring record with the same FAM type and code	'	)	,
	(	'	R59	'	,	'	W	'	,	'	The learner must not have more than one Learner Funding and Monitoring record with the same FAM type and code	'	)	,
	(	'	R61	'	,	'	E	'	,	'	The learner must not have more than one Learner Funding and Monitoring record with the same FAM type and code	'	)	,
	(	'	R62	'	,	'	E	'	,	'	The learner must not have more than one Learner Funding and Monitoring record with the same FAM type and code	'	)	,
	(	'	R63	'	,	'	E	'	,	'	The learner must not have more than one Learner Funding and Monitoring record with the same FAM type and code	'	)	,
	(	'	R64	'	,	'	E	'	,	'	The learner must not have more than one Learner Funding and Monitoring record with the same FAM type and code	'	)	,
	(	'	R66	'	,	'	E	'	,	'	The learner must not have more than one Learner Funding and Monitoring record with the same FAM type and code	'	)	,
	(	'	R67	'	,	'	E	'	,	'	The learner must not have more than one Learner Funding and Monitoring record with the same FAM type and code	'	)	,
	(	'	R68	'	,	'	E	'	,	'	The learner must not have more than one Apprenticeship Financial Record with the same Apprenticeship financial type, code and date	'	)	,
	(	'	R69	'	,	'	E	'	,	'	The learner must not have more than one DPOutcome record with the same Outcome type, code and start date	'	)	,
	(	'	R71	'	,	'	E	'	,	'	There must not be more than one Learner Destination and Progression record with the same Learner reference number	'	)	,
	(	'	R72	'	,	'	E	'	,	'	The payment amounts must not exceed the employer contribution proportion of the total negotiated price	'	)	,
	(	'	R73	'	,	'	E	'	,	'	The payment amounts must not exceed the employer contribution proportion of the total negotiated price	'	)	,
	(	'	R75	'	,	'	W	'	,	'	The sum of the Apprenticeship financial payment amounts should not be less than zero	'	)	,
	(	'	R85	'	,	'	E	'	,	'	The ULN for this learner must match between the Learner entity and the Learner Destination and Progression entity	'	)	,
	(	'	R89	'	,	'	E	'	,	'	The Learning actual end date for the latest programme aim must not be before the Learning actual end date of the latest component aim (not including English and maths)	'	)	,
	(	'	R90	'	,	'	E	'	,	'	The Learning actual end date of the component aims must be returned for this programme	'	)	,
	(	'	R91	'	,	'	E	'	,	'	There must be a completed ZESF0001 learning aim for this learner	'	)	,
	(	'	R92	'	,	'	E	'	,	'	There must not be more than one ZESF0001 learning aim for this contract	'	)	,
	(	'	R96	'	,	'	E	'	,	'	The learner must not have more than one Learning Delivery Work Placement record with the same Work placement start date	'	)	,
	(	'	R97	'	,	'	E	'	,	'	The learner must not have consecutive Learner Employment status records with the same Employment status, Employer identifier and Employment Status Monitoring	'	)	,
	(	'	R99	'	,	'	E	'	,	'	The learner must not have more than one programme aim at the same time	'	)	,
	(	'	R100	'	,	'	E	'	,	'	There must be an assessment price recorded	'	)	,
	(	'	R101	'	,	'	E	'	,	'	The learning aim must not have more than one Apprenticeship contract type record at the same time	'	)	,
	(	'	R102	'	,	'	E	'	,	'	The aim must have an Apprenticeship contract type in the first day	'	)	,
	(	'	R104	'	,	'	E	'	,	'	There must be an apprenticeship contract type for the full duration of the aim	'	)	,
	(	'	R105	'	,	'	E	'	,	'	The learner must not have different Apprenticeship contract types recorded at the same time	'	)	,
	(	'	R106	'	,	'	E	'	,	'	There must not be more than one LSF record at the same time	'	)	,
	(	'	R107	'	,	'	W	'	,	'	There should be a Learner Destination and Progression record present	'	)	,
	(	'	R108	'	,	'	E	'	,	'	There must be a Learner Destination and Progression record present	'	)	,
	(	'	R109	'	,	'	E	'	,	'	A learner cannot have aims that have a source of funding of 105 and 107 at the same time.	'	)	,
	(	'	R110	'	,	'	E	'	,	'	The employment status is not valid for this apprenticeship contract type	'	)	,
	(	'	R111	'	,	'	E	'	,	'	The apprenticeship contract type is not valid for this employment status	'	)	,
	(	'	R112	'	,	'	E	'	,	'	There must be a Date applies to that matches the Learning actual end date for this aim.	'	)	,
	(	'	R113	'	,	'	E	'	,	'	The Learning actual end date is not known, then the Date applies to record must not be returned.	'	)	,
	(	'	FD_LearnRefNumber_AP	'	,	'	E	'	,	'	The LearnRefNumber does not match the validation pattern	'	)	,
	(	'	FD_PrevLearnRefNumber_AP	'	,	'	E	'	,	'	The PrevLearnRefNumber does not match the validation pattern	'	)	,
	(	'	FD_FamilyName_AP	'	,	'	E	'	,	'	The FamilyName does not match the validation pattern	'	)	,
	(	'	FD_GivenNames_AP	'	,	'	E	'	,	'	The GivenNames does not match the validation pattern	'	)	,
	(	'	FD_Sex_AP	'	,	'	E	'	,	'	The Sex does not match the validation pattern	'	)	,
	(	'	FD_NINumber_AP	'	,	'	E	'	,	'	The NINumber does not match the validation pattern	'	)	,
	(	'	FD_MathGrade_AP	'	,	'	E	'	,	'	The MathGrade does not match the validation pattern	'	)	,
	(	'	FD_EngGrade_AP	'	,	'	E	'	,	'	The EngGrade does not match the validation pattern	'	)	,
	(	'	FD_PostcodePrior_AP	'	,	'	E	'	,	'	The PostcodePrior does not match the validation pattern	'	)	,
	(	'	FD_Postcode_AP	'	,	'	E	'	,	'	The Postcode does not match the validation pattern	'	)	,
	(	'	FD_AddLine1_AP	'	,	'	E	'	,	'	The AddLine1 does not match the validation pattern	'	)	,
	(	'	FD_AddLine2_AP	'	,	'	E	'	,	'	The AddLine2 does not match the validation pattern	'	)	,
	(	'	FD_AddLine3_AP	'	,	'	E	'	,	'	The AddLine3 does not match the validation pattern	'	)	,
	(	'	FD_AddLine4_AP	'	,	'	E	'	,	'	The AddLine4 does not match the validation pattern	'	)	,
	(	'	FD_TelNo_AP	'	,	'	E	'	,	'	The TelNo does not match the validation pattern	'	)	,
	(	'	FD_Email_AP	'	,	'	E	'	,	'	The Email does not match the validation pattern	'	)	,
	(	'	FD_ContPrefType_AP	'	,	'	E	'	,	'	The ContPrefType does not match the validation pattern	'	)	,
	(	'	FD_LearnFAMType_AP	'	,	'	E	'	,	'	The LearnFAMType does not match the validation pattern	'	)	,
	(	'	FD_ProvSpecLearnMonOccur_AP	'	,	'	E	'	,	'	The ProvSpecLearnMonOccur does not match the validation pattern	'	)	,
	(	'	FD_ProvSpecLearnMon_AP	'	,	'	E	'	,	'	The ProvSpecLearnMon does not match the validation pattern	'	)	,
	(	'	FD_ESMType_AP	'	,	'	E	'	,	'	The ESMType does not match the validation pattern	'	)	,
	(	'	FD_UCASPERID_AP	'	,	'	E	'	,	'	The UCASPERID does not match the validation pattern	'	)	,
	(	'	FD_LearnAimRef_AP	'	,	'	E	'	,	'	The LearnAimRef does not match the validation pattern	'	)	,
	(	'	FD_DelLocPostCode_AP	'	,	'	E	'	,	'	The DelLocPostCode does not match the validation pattern	'	)	,
	(	'	FD_ConRefNumber_AP	'	,	'	E	'	,	'	The ConRefNumber does not match the validation pattern	'	)	,
	(	'	FD_EPAOrgID_AP	'	,	'	E	'	,	'	The EPAOrgID does not match the validation pattern	'	)	,
	(	'	FD_OutGrade_AP	'	,	'	E	'	,	'	The OutGrade does not match the validation pattern	'	)	,
	(	'	FD_SWSupAimId_AP	'	,	'	E	'	,	'	The SWSupAimId does not match the validation pattern	'	)	,
	(	'	FD_LearnDelFAMType_AP	'	,	'	E	'	,	'	The LearnDelFAMType does not match the validation pattern	'	)	,
	(	'	FD_LearnDelFAMCode_AP	'	,	'	E	'	,	'	The LearnDelFAMCode does not match the validation pattern	'	)	,
	(	'	FD_AFinType_AP	'	,	'	E	'	,	'	The AFinType does not match the validation pattern	'	)	,
	(	'	FD_ProvSpecDelMonOccur_AP	'	,	'	E	'	,	'	The ProvSpecDelMonOccur does not match the validation pattern	'	)	,
	(	'	FD_ProvSpecDelMon_AP	'	,	'	E	'	,	'	The ProvSpecDelMon does not match the validation pattern	'	)	,
	(	'	FD_NUMHUS_AP	'	,	'	E	'	,	'	The NUMHUS does not match the validation pattern	'	)	,
	(	'	FD_SSN_AP	'	,	'	E	'	,	'	The SSN does not match the validation pattern	'	)	,
	(	'	FD_QUALENT3_AP	'	,	'	E	'	,	'	The QUALENT3 does not match the validation pattern	'	)	,
	(	'	FD_UCASAPPID_AP	'	,	'	E	'	,	'	The UCASAPPID does not match the validation pattern	'	)	,
	(	'	FD_DOMICILE_AP	'	,	'	E	'	,	'	The DOMICILE does not match the validation pattern	'	)	,
	(	'	FD_HEPostCode_AP	'	,	'	E	'	,	'	The HEPostCode does not match the validation pattern	'	)	,
	(	'	FD_DP_LearnRefNumber_AP	'	,	'	E	'	,	'	The LearnRefNumber does not match the validation pattern	'	)	,
	(	'	FD_DP_OutType_AP	'	,	'	E	'	,	'	The OutType does not match the validation pattern	'	)	,
	(	'	FD_LearnRefNumber_MA	'	,	'	E	'	,	'	The LearnRefNumber has not been returned	'	)	,
	(	'	FD_ULN_MA	'	,	'	E	'	,	'	The ULN has not been returned	'	)	,
	(	'	FD_Ethnicity_MA	'	,	'	E	'	,	'	The Ethnicity has not been returned	'	)	,
	(	'	FD_Sex_MA	'	,	'	E	'	,	'	The Sex has not been returned	'	)	,
	(	'	FD_LLDDHealthProb_MA	'	,	'	E	'	,	'	The LLDDHealthProb has not been returned	'	)	,
	(	'	FD_PostcodePrior_MA	'	,	'	E	'	,	'	The PostcodePrior has not been returned	'	)	,
	(	'	FD_Postcode_MA	'	,	'	E	'	,	'	The Postcode has not been returned	'	)	,
	(	'	FD_LearnRefNumber_AL	'	,	'	E	'	,	'	The length of the value returned for LearnRefNumber is not between 1 and 12 characters	'	)	,
	(	'	FD_PrevLearnRefNumber_AL	'	,	'	E	'	,	'	The length of the value returned for PrevLearnRefNumber is not between 1 and 12 characters	'	)	,
	(	'	FD_PrevUKPRN_AL	'	,	'	E	'	,	'	The length of the value returned for PrevUKPRN is not between 1 and 8 characters	'	)	,
	(	'	FD_PMUKPRN_AL	'	,	'	E	'	,	'	The length of the value returned for PMUKPRN is not between 1 and 8 characters	'	)	,
	(	'	FD_ULN_AL	'	,	'	E	'	,	'	The length of the value returned for ULN is not between 1 and 10 characters	'	)	,
	(	'	FD_FamilyName_AL	'	,	'	E	'	,	'	The length of the value returned for FamilyName is not between 1 and 100 characters	'	)	,
	(	'	FD_GivenNames_AL	'	,	'	E	'	,	'	The length of the value returned for GivenNames is not between 1 and 100 characters	'	)	,
	(	'	FD_Ethnicity_AL	'	,	'	E	'	,	'	The length of the value returned for Ethnicity is not between 1 and 2 characters	'	)	,
	(	'	FD_Sex_AL	'	,	'	E	'	,	'	The value returned for Sex is not 1 character long	'	)	,
	(	'	FD_LLDDHealthProb_AL	'	,	'	E	'	,	'	The value returned for LLDDHealthProb is not 1 character long	'	)	,
	(	'	FD_NINumber_AL	'	,	'	E	'	,	'	The length of the value returned for NINumber is not between 1 and 9 characters	'	)	,
	(	'	FD_PriorAttain_AL	'	,	'	E	'	,	'	The length of the value returned for PriorAttain is not between 1 and 2 characters	'	)	,
	(	'	FD_Accom_AL	'	,	'	E	'	,	'	The value returned for Accom is not 1 character long	'	)	,
	(	'	FD_ALSCost_AL	'	,	'	E	'	,	'	The length of the value returned for ALSCost is not between 1 and 6 characters	'	)	,
	(	'	FD_PlanLearnHours_AL	'	,	'	E	'	,	'	The length of the value returned for PlanLearnHours is not between 1 and 4 characters	'	)	,
	(	'	FD_PlanEEPHours_AL	'	,	'	E	'	,	'	The length of the value returned for PlanEEPHours is not between 1 and 4 characters	'	)	,
	(	'	FD_MathGrade_AL	'	,	'	E	'	,	'	The length of the value returned for MathGrade is not between 1 and 4 characters	'	)	,
	(	'	FD_EngGrade_AL	'	,	'	E	'	,	'	The length of the value returned for EngGrade is not between 1 and 4 characters	'	)	,
	(	'	FD_PostcodePrior_AL	'	,	'	E	'	,	'	The length of the value returned for PostcodePrior is not between 1 and 8 characters	'	)	,
	(	'	FD_Postcode_AL	'	,	'	E	'	,	'	The length of the value returned for Postcode is not between 1 and 8 characters	'	)	,
	(	'	FD_AddLine1_AL	'	,	'	E	'	,	'	The length of the value returned for AddLine1 is not between 1 and 50 characters	'	)	,
	(	'	FD_AddLine2_AL	'	,	'	E	'	,	'	The length of the value returned for AddLine2 is not between 1 and 50 characters	'	)	,
	(	'	FD_AddLine3_AL	'	,	'	E	'	,	'	The length of the value returned for AddLine3 is not between 1 and 50 characters	'	)	,
	(	'	FD_AddLine4_AL	'	,	'	E	'	,	'	The length of the value returned for AddLine4 is not between 1 and 50 characters	'	)	,
	(	'	FD_TelNo_AL	'	,	'	E	'	,	'	The length of the value returned for TelNo is not between 1 and 18 characters	'	)	,
	(	'	FD_Email_AL	'	,	'	E	'	,	'	The length of the value returned for Email is not between 1 and 100 characters	'	)	,
	(	'	FD_PrevUKPRN_AR	'	,	'	E	'	,	'	The PrevUKPRN is out of range	'	)	,
	(	'	FD_PMUKPRN_AR	'	,	'	E	'	,	'	The PMUKPRN is out of range	'	)	,
	(	'	FD_ULN_AR	'	,	'	E	'	,	'	The ULN is out of range	'	)	,
	(	'	FD_ALSCost_AR	'	,	'	E	'	,	'	The ALSCost is out of range	'	)	,
	(	'	FD_PlanLearnHours_AR	'	,	'	E	'	,	'	The PlanLearnHours is out of range	'	)	,
	(	'	FD_PlanEEPHours_AR	'	,	'	E	'	,	'	The PlanEEPHours is out of range	'	)	,
	(	'	FD_ContPrefType_MA	'	,	'	E	'	,	'	The ContPrefType has not been returned	'	)	,
	(	'	FD_ContPrefCode_MA	'	,	'	E	'	,	'	The ContPrefCode has not been returned	'	)	,
	(	'	FD_ContPrefType_AL	'	,	'	E	'	,	'	The length of the value returned for ContPrefType is not between 1 and 3 characters	'	)	,
	(	'	FD_ContPrefCode_AL	'	,	'	E	'	,	'	The value returned for ContPrefCode is not 1 character long	'	)	,
	(	'	FD_ContactPreference_EO	'	,	'	E	'	,	'	The ContactPreference has occurred more than allowed	'	)	,
	(	'	FD_LLDDCat_MA	'	,	'	E	'	,	'	The LLDDCat has not been returned	'	)	,
	(	'	FD_LLDDCat_AL	'	,	'	E	'	,	'	The length of the value returned for LLDDCat is not between 1 and 2 characters	'	)	,
	(	'	FD_PrimaryLLDD_AL	'	,	'	E	'	,	'	The value returned for PrimaryLLDD is not 1 character long	'	)	,
	(	'	FD_LLDDandHealthProblem_EO	'	,	'	E	'	,	'	The LLDDandHealthProblem has occurred more than allowed	'	)	,
	(	'	FD_LearnFAMType_MA	'	,	'	E	'	,	'	The LearnFAMType has not been returned	'	)	,
	(	'	FD_LearnFAMCode_MA	'	,	'	E	'	,	'	The LearnFAMCode has not been returned	'	)	,
	(	'	FD_LearnFAMType_AL	'	,	'	E	'	,	'	The length of the value returned for LearnFAMType is not between 1 and 3 characters	'	)	,
	(	'	FD_LearnFAMCode_AL	'	,	'	E	'	,	'	The length of the value returned for LearnFAMCode is not between 1 and 3 characters	'	)	,
	(	'	FD_LearnerFAM_EO	'	,	'	E	'	,	'	The LearnerFAM has occurred more than allowed	'	)	,
	(	'	FD_ProvSpecLearnMonOccur_MA	'	,	'	E	'	,	'	The ProvSpecLearnMonOccur has not been returned	'	)	,
	(	'	FD_ProvSpecLearnMon_MA	'	,	'	E	'	,	'	The ProvSpecLearnMon has not been returned	'	)	,
	(	'	FD_ProvSpecLearnMonOccur_AL	'	,	'	E	'	,	'	The value returned for ProvSpecLearnMonOccur is not 1 character long	'	)	,
	(	'	FD_ProvSpecLearnMon_AL	'	,	'	E	'	,	'	The length of the value returned for ProvSpecLearnMon is not between 1 and 20 characters	'	)	,
	(	'	FD_ProviderSpecLearnerMonitoring_EO	'	,	'	E	'	,	'	The ProviderSpecLearnerMonitoring has occurred more than allowed	'	)	,
	(	'	FD_EmpStat_MA	'	,	'	E	'	,	'	The EmpStat has not been returned	'	)	,
	(	'	FD_DateEmpStatApp_MA	'	,	'	E	'	,	'	The DateEmpStatApp has not been returned	'	)	,
	(	'	FD_EmpStat_AL	'	,	'	E	'	,	'	The length of the value returned for EmpStat is not between 1 and 2 characters	'	)	,
	(	'	FD_EmpId_AL	'	,	'	E	'	,	'	The length of the value returned for EmpId is not between 1 and 9 characters	'	)	,
	(	'	FD_ESMType_MA	'	,	'	E	'	,	'	The ESMType has not been returned	'	)	,
	(	'	FD_ESMCode_MA	'	,	'	E	'	,	'	The ESMCode has not been returned	'	)	,
	(	'	FD_ESMType_AL	'	,	'	E	'	,	'	The length of the value returned for ESMType is not between 1 and 3 characters	'	)	,
	(	'	FD_ESMCode_AL	'	,	'	E	'	,	'	The length of the value returned for ESMCode is not between 1 and 2 characters	'	)	,
	(	'	FD_EmploymentStatusMonitoring_EO	'	,	'	E	'	,	'	The EmploymentStatusMonitoring has occurred more than allowed	'	)	,
	(	'	FD_UCASPERID_AL	'	,	'	E	'	,	'	The length of the value returned for UCASPERID is not between 1 and 10 characters	'	)	,
	(	'	FD_TTACCOM_AL	'	,	'	E	'	,	'	The value returned for TTACCOM is not 1 character long	'	)	,
	(	'	FD_UCASPERID_AR	'	,	'	E	'	,	'	The UCASPERID is out of range	'	)	,
	(	'	FD_LearnerHE_EO	'	,	'	E	'	,	'	The LearnerHE has occurred more than allowed	'	)	,
	(	'	FD_FINTYPE_MA	'	,	'	E	'	,	'	The FINTYPE has not been returned	'	)	,
	(	'	FD_FINAMOUNT_MA	'	,	'	E	'	,	'	The FINAMOUNT has not been returned	'	)	,
	(	'	FD_FINTYPE_AL	'	,	'	E	'	,	'	The value returned for FINTYPE is not 1 character long	'	)	,
	(	'	FD_FINAMOUNT_AL	'	,	'	E	'	,	'	The length of the value returned for FINAMOUNT is not between 1 and 6 characters	'	)	,
	(	'	FD_FINAMOUNT_AR	'	,	'	E	'	,	'	The FINAMOUNT is out of range	'	)	,
	(	'	FD_LearnerHEFinancialSupport_EO	'	,	'	E	'	,	'	The LearnerHEFinancialSupport has occurred more than allowed	'	)	,
	(	'	FD_LearnAimRef_MA	'	,	'	E	'	,	'	The LearnAimRef has not been returned	'	)	,
	(	'	FD_AimType_MA	'	,	'	E	'	,	'	The AimType has not been returned	'	)	,
	(	'	FD_AimSeqNumber_MA	'	,	'	E	'	,	'	The AimSeqNumber has not been returned	'	)	,
	(	'	FD_LearnStartDate_MA	'	,	'	E	'	,	'	The LearnStartDate has not been returned	'	)	,
	(	'	FD_LearnPlanEndDate_MA	'	,	'	E	'	,	'	The LearnPlanEndDate has not been returned	'	)	,
	(	'	FD_FundModel_MA	'	,	'	E	'	,	'	The FundModel has not been returned	'	)	,
	(	'	FD_DelLocPostCode_MA	'	,	'	E	'	,	'	The DelLocPostCode has not been returned	'	)	,
	(	'	FD_CompStatus_MA	'	,	'	E	'	,	'	The CompStatus has not been returned	'	)	,
	(	'	FD_LearnAimRef_AL	'	,	'	E	'	,	'	The length of the value returned for LearnAimRef is not between 1 and 8 characters	'	)	,
	(	'	FD_AimType_AL	'	,	'	E	'	,	'	The value returned for AimType is not 1 character long	'	)	,
	(	'	FD_AimSeqNumber_AL	'	,	'	E	'	,	'	The length of the value returned for AimSeqNumber is not between 1 and 2 characters	'	)	,
	(	'	FD_FundModel_AL	'	,	'	E	'	,	'	The length of the value returned for FundModel is not between 1 and 2 characters	'	)	,
	(	'	FD_ProgType_AL	'	,	'	E	'	,	'	The length of the value returned for ProgType is not between 1 and 2 characters	'	)	,
	(	'	FD_FworkCode_AL	'	,	'	E	'	,	'	The length of the value returned for FworkCode is not between 1 and 3 characters	'	)	,
	(	'	FD_PwayCode_AL	'	,	'	E	'	,	'	The length of the value returned for PwayCode is not between 1 and 3 characters	'	)	,
	(	'	FD_StdCode_AL	'	,	'	E	'	,	'	The length of the value returned for StdCode is not between 1 and 5 characters	'	)	,
	(	'	FD_PartnerUKPRN_AL	'	,	'	E	'	,	'	The length of the value returned for PartnerUKPRN is not between 1 and 8 characters	'	)	,
	(	'	FD_DelLocPostCode_AL	'	,	'	E	'	,	'	The length of the value returned for DelLocPostCode is not between 1 and 8 characters	'	)	,
	(	'	FD_AddHours_AL	'	,	'	E	'	,	'	The length of the value returned for AddHours is not between 1 and 4 characters	'	)	,
	(	'	FD_PriorLearnFundAdj_AL	'	,	'	E	'	,	'	The length of the value returned for PriorLearnFundAdj is not between 1 and 2 characters	'	)	,
	(	'	FD_OtherFundAdj_AL	'	,	'	E	'	,	'	The length of the value returned for OtherFundAdj is not between 1 and 3 characters	'	)	,
	(	'	FD_ConRefNumber_AL	'	,	'	E	'	,	'	The length of the value returned for ConRefNumber is not between 1 and 20 characters	'	)	,
	(	'	FD_EPAOrgID_AL	'	,	'	E	'	,	'	The length of the value returned for EPAOrgID is not between 1 and 7 characters	'	)	,
	(	'	FD_EmpOutcome_AL	'	,	'	E	'	,	'	The value returned for EmpOutcome is not 1 character long	'	)	,
	(	'	FD_CompStatus_AL	'	,	'	E	'	,	'	The value returned for CompStatus is not 1 character long	'	)	,
	(	'	FD_WithdrawReason_AL	'	,	'	E	'	,	'	The length of the value returned for WithdrawReason is not between 1 and 2 characters	'	)	,
	(	'	FD_Outcome_AL	'	,	'	E	'	,	'	The value returned for Outcome is not 1 character long	'	)	,
	(	'	FD_OutGrade_AL	'	,	'	E	'	,	'	The length of the value returned for OutGrade is not between 1 and 6 characters	'	)	,
	(	'	FD_SWSupAimId_AL	'	,	'	E	'	,	'	The length of the value returned for SWSupAimId is not between 1 and 36 characters	'	)	,
	(	'	FD_AimSeqNumber_AR	'	,	'	E	'	,	'	The AimSeqNumber is out of range	'	)	,
	(	'	FD_PartnerUKPRN_AR	'	,	'	E	'	,	'	The PartnerUKPRN is out of range	'	)	,
	(	'	FD_AddHours_AR	'	,	'	E	'	,	'	The AddHours is out of range	'	)	,
	(	'	FD_PriorLearnFundAdj_AR	'	,	'	E	'	,	'	The PriorLearnFundAdj is out of range	'	)	,
	(	'	FD_OtherFundAdj_AR	'	,	'	E	'	,	'	The OtherFundAdj is out of range	'	)	,
	(	'	FD_LearningDelivery_EO	'	,	'	E	'	,	'	The LearningDelivery has not met the minimum occurrence requirement	'	)	,
	(	'	FD_LearnDelFAMType_MA	'	,	'	E	'	,	'	The LearnDelFAMType has not been returned	'	)	,
	(	'	FD_LearnDelFAMCode_MA	'	,	'	E	'	,	'	The LearnDelFAMCode has not been returned	'	)	,
	(	'	FD_LearnDelFAMType_AL	'	,	'	E	'	,	'	The length of the value returned for LearnDelFAMType is not between 1 and 3 characters	'	)	,
	(	'	FD_LearnDelFAMCode_AL	'	,	'	E	'	,	'	The length of the value returned for LearnDelFAMCode is not between 1 and 5 characters	'	)	,
	(	'	FD_WorkPlaceStartDate_MA	'	,	'	E	'	,	'	The WorkPlaceStartDate has not been returned	'	)	,
	(	'	FD_WorkPlaceHours_MA	'	,	'	E	'	,	'	The WorkPlaceHours has not been returned	'	)	,
	(	'	FD_WorkPlaceMode_MA	'	,	'	E	'	,	'	The WorkPlaceMode has not been returned	'	)	,
	(	'	FD_WorkPlaceHours_AL	'	,	'	E	'	,	'	The length of the value returned for WorkPlaceHours is not between 1 and 4 characters	'	)	,
	(	'	FD_WorkPlaceMode_AL	'	,	'	E	'	,	'	The value returned for WorkPlaceMode is not 1 character long	'	)	,
	(	'	FD_WorkPlaceEmpId_AL	'	,	'	E	'	,	'	The length of the value returned for WorkPlaceEmpId is not between 1 and 9 characters	'	)	,
	(	'	FD_WorkPlaceHours_AR	'	,	'	E	'	,	'	The WorkPlaceHours is out of range	'	)	,
	(	'	FD_AFinType_MA	'	,	'	E	'	,	'	The AFinType has not been returned	'	)	,
	(	'	FD_AFinCode_MA	'	,	'	E	'	,	'	The AFinCode has not been returned	'	)	,
	(	'	FD_AFinDate_MA	'	,	'	E	'	,	'	The AFinDate has not been returned	'	)	,
	(	'	FD_AFinAmount_MA	'	,	'	E	'	,	'	The AFinAmount has not been returned	'	)	,
	(	'	FD_AFinType_AL	'	,	'	E	'	,	'	The length of the value returned for AFinType is not between 1 and 3 characters	'	)	,
	(	'	FD_AFinCode_AL	'	,	'	E	'	,	'	The length of the value returned for AFinCode is not between 1 and 2 characters	'	)	,
	(	'	FD_AFinAmount_AL	'	,	'	E	'	,	'	The length of the value returned for AFinAmount is not between 1 and 6 characters	'	)	,
	(	'	FD_AFinAmount_AR	'	,	'	E	'	,	'	The AFinAmount is out of range	'	)	,
	(	'	FD_ProvSpecDelMonOccur_MA	'	,	'	E	'	,	'	The ProvSpecDelMonOccur has not been returned	'	)	,
	(	'	FD_ProvSpecDelMon_MA	'	,	'	E	'	,	'	The ProvSpecDelMon has not been returned	'	)	,
	(	'	FD_ProvSpecDelMonOccur_AL	'	,	'	E	'	,	'	The value returned for ProvSpecDelMonOccur is not 1 character long	'	)	,
	(	'	FD_ProvSpecDelMon_AL	'	,	'	E	'	,	'	The length of the value returned for ProvSpecDelMon is not between 1 and 20 characters	'	)	,
	(	'	FD_ProviderSpecDeliveryMonitoring_EO	'	,	'	E	'	,	'	The ProviderSpecDeliveryMonitoring has occurred more than allowed	'	)	,
	(	'	FD_TYPEYR_MA	'	,	'	E	'	,	'	The TYPEYR has not been returned	'	)	,
	(	'	FD_MODESTUD_MA	'	,	'	E	'	,	'	The MODESTUD has not been returned	'	)	,
	(	'	FD_FUNDLEV_MA	'	,	'	E	'	,	'	The FUNDLEV has not been returned	'	)	,
	(	'	FD_FUNDCOMP_MA	'	,	'	E	'	,	'	The FUNDCOMP has not been returned	'	)	,
	(	'	FD_YEARSTU_MA	'	,	'	E	'	,	'	The YEARSTU has not been returned	'	)	,
	(	'	FD_MSTUFEE_MA	'	,	'	E	'	,	'	The MSTUFEE has not been returned	'	)	,
	(	'	FD_SPECFEE_MA	'	,	'	E	'	,	'	The SPECFEE has not been returned	'	)	,
	(	'	FD_NUMHUS_AL	'	,	'	E	'	,	'	The length of the value returned for NUMHUS is not between 1 and 20 characters	'	)	,
	(	'	FD_SSN_AL	'	,	'	E	'	,	'	The length of the value returned for SSN is not between 1 and 13 characters	'	)	,
	(	'	FD_QUALENT3_AL	'	,	'	E	'	,	'	The length of the value returned for QUALENT3 is not between 1 and 3 characters	'	)	,
	(	'	FD_SOC2000_AL	'	,	'	E	'	,	'	The length of the value returned for SOC2000 is not between 1 and 4 characters	'	)	,
	(	'	FD_SEC_AL	'	,	'	E	'	,	'	The value returned for SEC is not 1 character long	'	)	,
	(	'	FD_UCASAPPID_AL	'	,	'	E	'	,	'	The length of the value returned for UCASAPPID is not between 1 and 9 characters	'	)	,
	(	'	FD_TYPEYR_AL	'	,	'	E	'	,	'	The value returned for TYPEYR is not 1 character long	'	)	,
	(	'	FD_MODESTUD_AL	'	,	'	E	'	,	'	The length of the value returned for MODESTUD is not between 1 and 2 characters	'	)	,
	(	'	FD_FUNDLEV_AL	'	,	'	E	'	,	'	The length of the value returned for FUNDLEV is not between 1 and 2 characters	'	)	,
	(	'	FD_FUNDCOMP_AL	'	,	'	E	'	,	'	The value returned for FUNDCOMP is not 1 character long	'	)	,
	(	'	FD_STULOAD_AL	'	,	'	E	'	,	'	The length of the value returned for STULOAD is not between 1 and 4 characters	'	)	,
	(	'	FD_YEARSTU_AL	'	,	'	E	'	,	'	The length of the value returned for YEARSTU is not between 1 and 2 characters	'	)	,
	(	'	FD_MSTUFEE_AL	'	,	'	E	'	,	'	The length of the value returned for MSTUFEE is not between 1 and 2 characters	'	)	,
	(	'	FD_PCOLAB_AL	'	,	'	E	'	,	'	The length of the value returned for PCOLAB is not between 1 and 4 characters	'	)	,
	(	'	FD_PCFLDCS_AL	'	,	'	E	'	,	'	The length of the value returned for PCFLDCS is not between 1 and 4 characters	'	)	,
	(	'	FD_PCSLDCS_AL	'	,	'	E	'	,	'	The length of the value returned for PCSLDCS is not between 1 and 4 characters	'	)	,
	(	'	FD_PCTLDCS_AL	'	,	'	E	'	,	'	The length of the value returned for PCTLDCS is not between 1 and 4 characters	'	)	,
	(	'	FD_SPECFEE_AL	'	,	'	E	'	,	'	The value returned for SPECFEE is not 1 character long	'	)	,
	(	'	FD_NETFEE_AL	'	,	'	E	'	,	'	The length of the value returned for NETFEE is not between 1 and 6 characters	'	)	,
	(	'	FD_GROSSFEE_AL	'	,	'	E	'	,	'	The length of the value returned for GROSSFEE is not between 1 and 6 characters	'	)	,
	(	'	FD_DOMICILE_AL	'	,	'	E	'	,	'	The length of the value returned for DOMICILE is not between 1 and 2 characters	'	)	,
	(	'	FD_ELQ_AL	'	,	'	E	'	,	'	The value returned for ELQ is not 1 character long	'	)	,
	(	'	FD_HEPostCode_AL	'	,	'	E	'	,	'	The length of the value returned for HEPostCode is not between 1 and 8 characters	'	)	,
	(	'	FD_STULOAD_AR	'	,	'	E	'	,	'	The STULOAD is out of range	'	)	,
	(	'	FD_YEARSTU_AR	'	,	'	E	'	,	'	The YEARSTU is out of range	'	)	,
	(	'	FD_PCOLAB_AR	'	,	'	E	'	,	'	The PCOLAB is out of range	'	)	,
	(	'	FD_PCFLDCS_AR	'	,	'	E	'	,	'	The PCFLDCS is out of range	'	)	,
	(	'	FD_PCSLDCS_AR	'	,	'	E	'	,	'	The PCSLDCS is out of range	'	)	,
	(	'	FD_PCTLDCS_AR	'	,	'	E	'	,	'	The PCTLDCS is out of range	'	)	,
	(	'	FD_NETFEE_AR	'	,	'	E	'	,	'	The NETFEE is out of range	'	)	,
	(	'	FD_GROSSFEE_AR	'	,	'	E	'	,	'	The GROSSFEE is out of range	'	)	,
	(	'	FD_LearningDeliveryHE_EO	'	,	'	E	'	,	'	The LearningDeliveryHE has occurred more than allowed	'	)	,
	(	'	FD_DP_LearnRefNumber_MA	'	,	'	E	'	,	'	The LearnRefNumber has not been returned	'	)	,
	(	'	FD_DP_ULN_MA	'	,	'	E	'	,	'	The ULN has not been returned	'	)	,
	(	'	FD_DP_LearnRefNumber_AL	'	,	'	E	'	,	'	The length of the value returned for LearnRefNumber is not between 1 and 12 characters	'	)	,
	(	'	FD_DP_ULN_AL	'	,	'	E	'	,	'	The length of the value returned for ULN is not between 1 and 10 characters	'	)	,
	(	'	FD_DP_ULN_AR	'	,	'	E	'	,	'	The ULN is out of range	'	)	,
	(	'	FD_DP_OutType_MA	'	,	'	E	'	,	'	The OutType has not been returned	'	)	,
	(	'	FD_DP_OutCode_MA	'	,	'	E	'	,	'	The OutCode has not been returned	'	)	,
	(	'	FD_DP_OutStartDate_MA	'	,	'	E	'	,	'	The OutStartDate has not been returned	'	)	,
	(	'	FD_DP_OutCollDate_MA	'	,	'	E	'	,	'	The OutCollDate has not been returned	'	)	,
	(	'	FD_DP_OutType_AL	'	,	'	E	'	,	'	The length of the value returned for OutType is not between 1 and 3 characters	'	)	,
	(	'	FD_DP_OutCode_AL	'	,	'	E	'	,	'	The length of the value returned for OutCode is not between 1 and 3 characters	'	)	,
	(	'	FD_DP_DPOutcome_EO	'	,	'	E	'	,	'	The DPOutcome has not met the minimum occurrence requirement	'	)	,
	(	'	DLOCK_01	'	,	'	W	'	,	'	No matching UKPRN record found	'	)	,
	(	'	DLOCK_02	'	,	'	W	'	,	'	No matching ULN found	'	)	,
	(	'	DLOCK_03	'	,	'	W	'	,	'	No matching standard code found	'	)	,
	(	'	DLOCK_04	'	,	'	W	'	,	'	No matching framework code found	'	)	,
	(	'	DLOCK_05	'	,	'	W	'	,	'	No matching programme type code found	'	)	,
	(	'	DLOCK_06	'	,	'	W	'	,	'	No matching pathway code found	'	)	,
	(	'	DLOCK_07	'	,	'	W	'	,	'	No matching negotiated cost of training and assessment found	'	)	,
	(	'	DLOCK_08	'	,	'	W	'	,	'	Multiple matching records found	'	)	,
	(	'	DLOCK_09	'	,	'	W	'	,	'	The learning delivery start month is before the agreed start month	'	)	,
	(	'	DLOCK_10	'	,	'	W	'	,	'	The employer has stopped payments for this apprentice	'	)	,
	(	'	DLOCK_11	'	,	'	W	'	,	'	The employer is not currently a levy payer	'	)	

go