-- =====================================================================================================
-- Generated by Data Dictionary Version 1.0.0.0
-- Date: 17 May 2017 14:51
-- Profile: DCSS Validation
-- Rulebase Version: ILR Validation DP 1718, Version 1718.01
-- =====================================================================================================
if not exists(select schema_id from sys.schemas where name='Rulebase')
	exec('create schema Rulebase')
go
if object_id('[Rulebase].[VALDP_Cases]','u') is not null
	drop table [Rulebase].[VALDP_Cases]
create table [Rulebase].[VALDP_Cases]
	(
		[LearnerDestinationAndProgression_Id] [int] primary key,
		[CaseData] [xml] not null
	)
go
if object_id('[Rulebase].[VALDP_global]','u') is not null
	drop table [Rulebase].[VALDP_global]
create table [Rulebase].[VALDP_global]
	(
		[UKPRN] int,
		[OrgVersion] varchar(50),
		[RulebaseVersion] varchar(10),
		[ULNVersion] varchar(50)
	)
go
if object_id('[Rulebase].[VALDP_ValidationError]','u') is not null
	drop table [Rulebase].[VALDP_ValidationError]
create table [Rulebase].[VALDP_ValidationError]
	(
		[ErrorString] varchar(2000),
		[FieldValues] varchar(2000),
		[LearnRefNumber] varchar(100),
		[RuleId] varchar(50)
	)
go
