-- =====================================================================================================
-- Generated by Data Dictionary Version 1.0.0.0
-- Date: 13 July 2016 08:30
-- Profile: 1516 Test Harness Calculation
-- Rulebase Version: ILR EFA Periodisation 1617, Drop 000, Version 1617.01
-- =====================================================================================================
use [$(IntrajobDatabase)]
go
insert into
	[Input].[LearningProvider]
		(
			[LearningProvider_Id],
			[UKPRN]
		)
select
	[PK_LearningProvider],
	[UKPRN]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearningProvider]
go

insert into
	[Input].[Learner]
		(
			[Learner_Id],
			[LearnRefNumber],
			ULN,
			Ethnicity,
			Sex,
			LLDDHealthProb
		)
select
	[PK_Learner],
	[LearnRefNumber],
	ULN,
	Ethnicity,
	Sex,
	LLDDHealthProb
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[Learner]
go

