-- =====================================================================================================
-- Generated by Data Dictionary Version 1.0.0.0
-- Date: 18 July 2016 10:27
-- Profile: 1516 Test Harness Validation
-- Rulebase Version: ILR Trailblazer Validation 1617, Drop 000, Version 1617.03
-- =====================================================================================================
use [$(IntrajobDatabase)]
go
insert into
	[Valid].[CollectionDetails]
		(
			[CollectionDetails_Id],
			[FilePreparationDate]
		)
select
	[CollectionDetails_Id],
	[FilePreparationDate]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[CollectionDetailsDenorm] CollectionDetails
where
	[CollectionDetails].[UKPRN]=$(UKPRN)
go

insert into
	[Valid].[LearningProvider]
		(
			[LearningProvider_Id],
			[UKPRN]
		)
select
	[LearningProvider_Id],
	[UKPRN]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearningProviderDenorm] LearningProvider
where
	[LearningProvider].[UKPRN]=$(UKPRN)
go

insert into
	[Valid].[Learner]
		(
			[Learner_Id],
			[LearnRefNumber]
		)
select
	[Learner_Id],
	[LearnRefNumber]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearnerDenorm] Learner
where
	[Learner].[UKPRN]=$(UKPRN)
go

insert into
	[Valid].[LearnerEmploymentStatus]
		(
			[LearnerEmploymentStatus_Id],
			[DateEmpStatApp]
		)
select
	[LearnerEmploymentStatus_Id],
	[DateEmpStatApp]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearnerEmploymentStatusDenorm] LearnerEmploymentStatus
where
	[LearnerEmploymentStatus].[UKPRN]=$(UKPRN)
go

insert into
	[Valid].[EmploymentStatusMonitoring]
		(
			[EmploymentStatusMonitoring_Id],
			[ESMCode],
			[ESMType]
		)
select
	[EmploymentStatusMonitoring_Id],
	[ESMCode],
	[ESMType]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[EmploymentStatusMonitoringDenorm] EmploymentStatusMonitoring
where
	[EmploymentStatusMonitoring].[UKPRN]=$(UKPRN)
go

insert into
	[Valid].[LearningDelivery]
		(
			[LearningDelivery_Id],
			[AimSeqNumber],
			[AimType],
			[CompStatus],
			[FundModel],
			[LearnActEndDate],
			[LearnAimRef],
			[LearnPlanEndDate],
			[LearnStartDate],
			[OrigLearnStartDate],
			[ProgType],
			[StdCode]
		)
select
	[LearningDelivery_Id],
	[AimSeqNumber],
	[AimType],
	[CompStatus],
	[FundModel],
	[LearnActEndDate],
	[LearnAimRef],
	[LearnPlanEndDate],
	[LearnStartDate],
	[OrigLearnStartDate],
	[ProgType],
	[StdCode]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearningDeliveryDenorm] LearningDelivery
where
	[LearningDelivery].[UKPRN]=$(UKPRN)
go

insert into
	[Valid].[TrailblazerApprenticeshipFinancialRecord]
		(
			[TrailblazerApprenticeshipFinancialRecord_Id],
			[TBFinAmount],
			[TBFinCode],
			[TBFinDate],
			[TBFinType]
		)
select
	[TrailblazerApprenticeshipFinancialRecord_Id],
	[TBFinAmount],
	[TBFinCode],
	[TBFinDate],
	[TBFinType]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[TrailblazerApprenticeshipFinancialRecordDenorm] TrailblazerApprenticeshipFinancialRecord
where
	[TrailblazerApprenticeshipFinancialRecord].[UKPRN]=$(UKPRN)
go

insert into
	[Valid].[LearningDeliveryFAM]
		(
			[LearningDeliveryFAM_Id],
			[LearnDelFAMCode],
			[LearnDelFAMDateFrom],
			[LearnDelFAMDateTo],
			[LearnDelFAMType]
		)
select
	[LearningDeliveryFAM_Id],
	[LearnDelFAMCode],
	[LearnDelFAMDateFrom],
	[LearnDelFAMDateTo],
	[LearnDelFAMType]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearningDeliveryFAMDenorm] LearningDeliveryFAM
where
	[LearningDeliveryFAM].[UKPRN]=$(UKPRN)
go

