-- =====================================================================================================
-- Generated by Data Dictionary Version 1.0.0.0
-- Date: 24 August 2016 12:03
-- Profile: Test Harness Calculation
-- Rulebase Version: ILR EFA Calculation 1617, Drop 000, Version 1617.04
-- =====================================================================================================
use [$(IntrajobDatabase)]
go
insert into
	[Valid].[LearningProvider]
		(
			[UKPRN]
		)
select
	[UKPRN]
from
	[$(FromILRDatabase)].Valid.[LearningProvider]
where
	[LearningProvider].[UKPRN]=$(UKPRN)
go

insert into
	[Valid].[Learner]
		(
			UKPRN, 
			LearnRefNumber, 
			PrevLearnRefNumber, 
			PrevUKPRN, 
			PMUKPRN, 
			ULN, 
			FamilyName, 
			GivenNames, 
			DateOfBirth, 
			Ethnicity, 
			Sex, 
			LLDDHealthProb, 
			NINumber, 
			PriorAttain, 
			Accom, 
			ALSCost, 
			PlanLearnHours, 
			PlanEEPHours, 
			MathGrade, 
			EngGrade, 
			PostcodePrior, 
			Postcode, 
			AddLine1, 
			AddLine2, 
			AddLine3, 
			AddLine4,
			TelNo, 
			Email
		)
select distinct
		UKPRN, 
		LearnRefNumber, 
		PrevLearnRefNumber, 
		PrevUKPRN, 
		PMUKPRN, 
		ULN, 
		FamilyName, 
		GivenNames, 
		DateOfBirth, 
		Ethnicity, 
		Sex, 
		LLDDHealthProb, 
		NINumber, 
		PriorAttain, 
		Accom, 
		ALSCost, 
		PlanLearnHours, 
		PlanEEPHours, 
		MathGrade, 
		EngGrade, 
		PostcodePrior, 
		Postcode, 
		AddLine1, 
		AddLine2, 
		AddLine3, 
		AddLine4,
		TelNo, 
		Email
FROM
	[$(FromILRDatabase)].Valid.[Learner] Learner
where
	[Learner].[UKPRN]=$(UKPRN)
go

insert into
	[Valid].[LearningDelivery]
		(
			UKPRN,
			[LearnRefNumber],
			[LearnAimRef],
			[AimType],
			[AimSeqNumber] ,
			[LearnStartDate] ,
			[OrigLearnStartDate],
			[LearnPlanEndDate],
			[FundModel],
			[ProgType],
			[FworkCode],
			[PwayCode],
			[StdCode] ,
			[PartnerUKPRN] ,
			[DelLocPostCode],
			[AddHours],
			[PriorLearnFundAdj],
			[OtherFundAdj] ,
			[ConRefNumber],
			[EPAOrgID],
			[EmpOutcome],
			[CompStatus] ,
			[LearnActEndDate],
			[WithdrawReason],
			[Outcome],
			[AchDate],
			[OutGrade],
			[SWSupAimId]
		)
select
		UKPRN,
		[LearnRefNumber],
		[LearnAimRef],
		[AimType],
		[AimSeqNumber] ,
		[LearnStartDate] ,
		[OrigLearnStartDate],
		[LearnPlanEndDate],
		[FundModel],
		[ProgType],
		[FworkCode],
		[PwayCode],
		[StdCode] ,
		[PartnerUKPRN] ,
		[DelLocPostCode],
		[AddHours],
		[PriorLearnFundAdj],
		[OtherFundAdj] ,
		[ConRefNumber],
		[EPAOrgID],
		[EmpOutcome],
		[CompStatus] ,
		[LearnActEndDate],
		[WithdrawReason],
		[Outcome],
		[AchDate],
		[OutGrade],
		[SWSupAimId]
from
	[$(FromILRDatabase)].Valid.[LearningDelivery] LearningDelivery
where
	[LearningDelivery].[UKPRN]=$(UKPRN)
GO

INSERT INTO 
	Valid.LearnerFAM
	(
		UKPRN
		,LearnRefNumber
		,LearnFAMType
		,LearnFAMCode
	)
SELECT
	UKPRN
	,LearnRefNumber
	,LearnFAMType
	,LearnFAMCode
FROM
	[$(FromILRDatabase)].Valid.LearnerFAM
WHERE
	LearnerFAM.UKPRN = $(UKPRN)
GO

INSERT INTO 
	Valid.LearningDeliveryFAM
	(
		UKPRN
		,LearnRefNumber
		,AimSeqNumber
		,LearnDelFAMType
		,LearnDelFAMCode
		,LearnDelFAMDateFrom
		,LearnDelFAMDateTo
	)
SELECT
	UKPRN
	,LearnRefNumber
	,AimSeqNumber
	,LearnDelFAMType
	,LearnDelFAMCode
	,LearnDelFAMDateFrom
	,LearnDelFAMDateTo
FROM
	[$(FromILRDatabase)].Valid.LearningDeliveryFAM
WHERE
	LearningDeliveryFAM.UKPRN = $(UKPRN)
go

insert into
	[Valid].[DPOutcome]
		(
			[UKPRN],
			[LearnRefNumber],
			[OutType],
			[OutCode],
			[OutStartDate],
			[OutCollDate]
		)
SELECT
	[UKPRN],
	[LearnRefNumber],
	[OutType],
	[OutCode],
	[OutStartDate],
	[OutCollDate]
from
	[$(FromILRDatabase)].Valid.[DPOutcome]
where
	[DPOutcome].[UKPRN]=$(UKPRN)
go

