-- =====================================================================================================
-- Generated by Data Dictionary Version 1.0.0.0
-- Date: 12 September 2016 10:58
-- Profile: Test Harness Calculation
-- Rulebase Version: ILR Derived Variables 1617, Drop 000, Version 1617.03
-- =====================================================================================================
use [$(IntrajobDatabase)]
go
insert into
	[Input].[LearningProvider]
		(
			[LearningProvider_Id],
			[UKPRN]
		)
select
	[PK_LearningProvider],
	[UKPRN]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearningProvider]
go

insert into
	[Input].[Learner]
		(
			[Learner_Id],
			[LearnRefNumber],
			[DateOfBirth],
			[Ethnicity],
			[LLDDHealthProb],
			[PlanEEPHours],
			[PlanLearnHours],
			[PrevLearnRefNumber],
			[PrevUKPRN],
			[PriorAttain],
			[ULN]
		)
select
	[PK_Learner],
	[LearnRefNumber],
	[DateOfBirth],
	[Ethnicity],
	[LLDDHealthProb],
	[PlanEEPHours],
	[PlanLearnHours],
	[PrevLearnRefNumber],
	[PrevUKPRN],
	[PriorAttain],
	[ULN]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[Learner]
go

insert into
	[Input].[LearnerEmploymentStatus]
		(
			[LearnerEmploymentStatus_Id],
			[Learner_Id],
			[DateEmpStatApp],
			[EmpId],
			[EmpStat]
		)
select
	[PK_LearnerEmploymentStatus],
	[FK_Learner],
	[DateEmpStatApp],
	[EmpId],
	[EmpStat]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearnerEmploymentStatus]
go

insert into
	[Input].[EmploymentStatusMonitoring]
		(
			[EmploymentStatusMonitoring_Id],
			[LearnerEmploymentStatus_Id],
			[ESMType],
			[ESMCode]
		)
select
	[PK_EmploymentStatusMonitoring],
	[FK_LearnerEmploymentStatus],
	[ESMType],
	[ESMCode]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[EmploymentStatusMonitoring]
go

insert into
	[Input].[ContactPreference]
		(
			[ContactPreference_Id],
			[Learner_Id],
			[ContPrefType],
			[ContPrefCode]
		)
select
	[PK_ContactPreference],
	[FK_Learner],
	[ContPrefType],
	[ContPrefCode]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[ContactPreference]
go

insert into
	[Input].[LearningDelivery]
		(
			[LearningDelivery_Id],
			[Learner_Id],
			[AimSeqNumber],
			[AimType],
			[CompStatus],
			[LearnAimRef],
			[FworkCode],
			[ProgType],
			[PwayCode],
			[FundModel],
			[LearnActEndDate],
			[LearnPlanEndDate],
			[LearnStartDate],
			[OrigLearnStartDate],
			[Outcome],
			[OutGrade],
			[WithdrawReason]
		)
select
	[PK_LearningDelivery],
	[FK_Learner],
	[AimSeqNumber],
	[AimType],
	[CompStatus],
	[LearnAimRef],
	[FworkCode],
	[ProgType],
	[PwayCode],
	[FundModel],
	[LearnActEndDate],
	[LearnPlanEndDate],
	[LearnStartDate],
	[OrigLearnStartDate],
	[Outcome],
	[OutGrade],
	[WithdrawReason]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearningDelivery]
go

insert into
	[Input].[LearningDeliveryFAM]
		(
			[LearningDeliveryFAM_Id],
			[LearningDelivery_Id],
			[LearnDelFAMType],
			[LearnDelFAMDateFrom],
			[LearnDelFAMCode],
			[LearnDelFAMDateTo]
		)
select
	[PK_LearningDeliveryFAM],
	[FK_LearningDelivery],
	[LearnDelFAMType],
	[LearnDelFAMDateFrom],
	[LearnDelFAMCode],
	[LearnDelFAMDateTo]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearningDeliveryFAM]
go

insert into
	[Input].[LearningDeliveryHE]
		(
			[LearningDeliveryHE_Id],
			[LearningDelivery_Id],
			[TYPEYR]
		)
select
	[PK_LearningDeliveryHE],
	[FK_LearningDelivery],
	[TYPEYR]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearningDeliveryHE]
go

insert into
	[Input].[LLDDandHealthProblem]
		(
			[LLDDandHealthProblem_Id],
			[Learner_Id],
			[LLDDCat],
			[PrimaryLLDD]
		)
select
	[PK_LLDDandHealthProblem],
	[FK_Learner],
	[LLDDCat],
	[PrimaryLLDD]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LLDDandHealthProblem]
go

