-- =====================================================================================================
-- Generated by Data Dictionary Version 1.0.0.0
-- Date: 12 September 2016 10:59
-- Profile: Test Harness Calculation
-- Rulebase Version: ILR Derived Variables 1617, Drop 000, Version 1617.03
-- =====================================================================================================
use [$(IntrajobDatabase)]
go
insert into
	[Valid].[LearningProvider]
		(
			[UKPRN]
		)
select
	[UKPRN]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearningProvider]
where
	[LearningProvider].[UKPRN]=$(UKPRN)
go

insert into
	[Valid].[Learner]
		(
			[LearnRefNumber],
			[DateOfBirth],
			[Ethnicity],
			[LLDDHealthProb],
			[PlanEEPHours],
			[PlanLearnHours],
			[PrevLearnRefNumber],
			[PrevUKPRN],
			[PriorAttain],
			[ULN]
		)
select
	[LearnRefNumber],
	[DateOfBirth],
	[Ethnicity],
	[LLDDHealthProb],
	[PlanEEPHours],
	[PlanLearnHours],
	[PrevLearnRefNumber],
	[PrevUKPRN],
	[PriorAttain],
	[ULN]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[Learner]
where
	[Learner].[UKPRN]=$(UKPRN)
go

insert into
	[Valid].[LearnerEmploymentStatus]
		(
			[LearnRefNumber],
			[DateEmpStatApp],
			[EmpId],
			[EmpStat],
			[EmpStatMon_BSI],
			[EmpStatMon_EII],
			[EmpStatMon_LOE],
			[EmpStatMon_LOU],
			[EmpStatMon_PEI],
			[EmpStatMon_SEI],
			[EmpStatMon_SEM]
		)
select
	[LearnRefNumber],
	[DateEmpStatApp],
	[EmpId],
	[EmpStat],
	[EmpStatMon_BSI],
	[EmpStatMon_EII],
	[EmpStatMon_LOE],
	[EmpStatMon_LOU],
	[EmpStatMon_PEI],
	[EmpStatMon_SEI],
	[EmpStatMon_SEM]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearnerEmploymentStatusDenorm] LearnerEmploymentStatus
where
	[LearnerEmploymentStatus].[UKPRN]=$(UKPRN)
go

insert into
	[Valid].[ContactPreference]
		(
			[ContPrefCode],
			[ContPrefType]
		)
select
	[ContPrefCode],
	[ContPrefType]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[ContactPreference]
where
	[ContactPreference].[UKPRN]=$(UKPRN)
go

insert into
	[Valid].[LearningDelivery]
		(
			[LearnRefNumber],
			[AimSeqNumber],
			[AimType],
			[CompStatus],
			[LearnAimRef],
			[FworkCode],
			[ProgType],
			[PwayCode],
			[FundModel],
			[LearnActEndDate],
			[LearnPlanEndDate],
			[LearnStartDate],
			[LrnDelFAM_ADL],
			[LrnDelFAM_EEF],
			[LrnDelFAM_FFI],
			[LrnDelFAM_LDM1],
			[LrnDelFAM_LDM2],
			[LrnDelFAM_LDM3],
			[LrnDelFAM_LDM4],
			[LrnDelFAM_RES],
			[LrnDelFAM_SOF],
			[LrnDelFAM_SPP],
			[OrigLearnStartDate],
			[Outcome],
			[OutGrade],
			[WithdrawReason]
		)
select
	[LearnRefNumber],
	[AimSeqNumber],
	[AimType],
	[CompStatus],
	[LearnAimRef],
	[FworkCode],
	[ProgType],
	[PwayCode],
	[FundModel],
	[LearnActEndDate],
	[LearnPlanEndDate],
	[LearnStartDate],
	[LrnDelFAM_ADL],
	[LrnDelFAM_EEF],
	[LrnDelFAM_FFI],
	[LrnDelFAM_LDM1],
	[LrnDelFAM_LDM2],
	[LrnDelFAM_LDM3],
	[LrnDelFAM_LDM4],
	[LrnDelFAM_RES],
	[LrnDelFAM_SOF],
	[LrnDelFAM_SPP],
	[OrigLearnStartDate],
	[Outcome],
	[OutGrade],
	[WithdrawReason]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearningDeliveryDenorm] LearningDelivery
where
	[LearningDelivery].[UKPRN]=$(UKPRN)
go

insert into
	[Valid].[LearningDeliveryFAM]
		(
			[LearnDelFAMCode],
			[LearnDelFAMDateFrom],
			[LearnDelFAMDateTo],
			[LearnDelFAMType]
		)
select
	[LearnDelFAMCode],
	[LearnDelFAMDateFrom],
	[LearnDelFAMDateTo],
	[LearnDelFAMType]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearningDeliveryFAM]
where
	[LearningDeliveryFAM].[UKPRN]=$(UKPRN)
go

insert into
	[Valid].[LearningDeliveryHE]
		(
			[LearnRefNumber],
			[AimSeqNumber],
			[TYPEYR]
		)
select
	[LearnRefNumber],
	[AimSeqNumber],
	[TYPEYR]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearningDeliveryHE]
where
	[LearningDeliveryHE].[UKPRN]=$(UKPRN)
go

insert into
	[Valid].[LLDDandHealthProblem]
		(
			[LearnRefNumber],
			[LLDDCat],
			[PrimaryLLDD]
		)
select
	[LearnRefNumber],
	[LLDDCat],
	[PrimaryLLDD]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LLDDandHealthProblem]
where
	[LLDDandHealthProblem].[UKPRN]=$(UKPRN)
go

