-- =====================================================================================================
-- Generated by Data Dictionary Version 1.0.0.0
-- Date: 20 December 2016 11:12
-- Profile: Test Harness Calculation
-- Rulebase Version: ILR ESF Funding Calc 1617, Version 1617.06
-- =====================================================================================================
use [$(IntrajobDatabase)]
go
insert into
	[Input].[LearningProvider]
		(
			[LearningProvider_Id],
			[UKPRN]
		)
select
	[PK_LearningProvider],
	[UKPRN]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearningProvider]
go

insert into
	[Input].[Learner]
		(
			[Learner_Id],
			[LearnRefNumber],
			[DateOfBirth],
			Ethnicity,
			Sex,
			LLDDHealthProb,
			ULN
		)
select
	[PK_Learner],
	[LearnRefNumber],
	[DateOfBirth],
	Ethnicity,
	Sex,
	LLDDHealthProb,
	ULN
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[Learner]
go

insert into
	[Input].[LearningDelivery]
		(
			[LearningDelivery_Id],
			[Learner_Id],
			[AimSeqNumber],
			LearnRefNumber,
			AimType,
			[AchDate],
			[AddHours],
			[ConRefNumber],
			[CompStatus],
			[LearnAimRef],
			[LearnActEndDate],
			[LearnPlanEndDate],
			[LearnStartDate],
			[OrigLearnStartDate],
			[OtherFundAdj],
			[Outcome],
			[PriorLearnFundAdj],
			[DelLocPostCode],
			[FundModel]
		)
select
	[PK_LearningDelivery],
	[FK_Learner],
	[AimSeqNumber],
	Learner.LearnRefNumber,
	AimType,
	[AchDate],
	[AddHours],
	[ConRefNumber],
	[CompStatus],
	[LearnAimRef],
	[LearnActEndDate],
	[LearnPlanEndDate],
	[LearnStartDate],
	[OrigLearnStartDate],
	[OtherFundAdj],
	[Outcome],
	[PriorLearnFundAdj],
	[DelLocPostCode],
	[FundModel]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearningDelivery]
	join [$(FromILRDatabase)].[$(FromILRSchema)].Learner
		on Learner.PK_Learner = LearningDelivery.FK_Learner
go

insert into
	[Input].[LearningDeliveryFAM]
		(
			[LearningDeliveryFAM_Id],
			[LearningDelivery_Id],
			LearnRefNumber,
			AimSeqNumber,
			[LearnDelFAMType],
			[LearnDelFAMDateFrom],
			[LearnDelFAMCode]
		)
select
	[PK_LearningDeliveryFAM],
	[FK_LearningDelivery],
	Learner.LearnRefNumber,
	AimSeqNumber,
	[LearnDelFAMType],
	[LearnDelFAMDateFrom],
	[LearnDelFAMCode]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearningDeliveryFAM]
	join [$(FromILRDatabase)].[$(FromILRSchema)].LearningDelivery
		on LearningDelivery.PK_LearningDelivery = LearningDeliveryFAM.FK_LearningDelivery
	join [$(FromILRDatabase)].[$(FromILRSchema)].Learner
		on Learner.PK_Learner = LearningDelivery.FK_Learner
go

insert into
	[Input].[DPOutcome]
		(
			[DPOutcome_Id],
			[LearnerDestinationandProgression_Id],
			LearnRefNumber,
			[OutType],
			[OutCode],
			[OutStartDate],
			[OutCollDate],
			[OutEndDate]
		)
select
	[PK_DPOutcome],
	[FK_LearnerDestinationandProgression],
	LearnerDestinationandProgression.LearnRefNumber,
	[OutType],
	[OutCode],
	[OutStartDate],
	[OutCollDate],
	[OutEndDate]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[DPOutcome]
	join [$(FromILRDatabase)].[$(FromILRSchema)].LearnerDestinationandProgression
		on LearnerDestinationandProgression.PK_LearnerDestinationandProgression = DPOutcome.FK_LearnerDestinationandProgression

go

insert into
	[Input].[LearnerDestinationandProgression]
		(
			[LearnerDestinationandProgression_Id],
			[LearnRefNumber]
		)
select
	[PK_LearnerDestinationandProgression],
	[LearnRefNumber]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearnerDestinationandProgression]
go

