-- =====================================================================================================
-- Generated by Data Dictionary Version 1.0.0.0
-- Date: 08 April 2016 14:18
-- Profile: 1516 Test Harness Calculation
-- Rulebase Version: DCSS 1516 ESF Funding Calc 1516, Drop 000, Version 1516.13
-- =====================================================================================================
use [$(IntrajobDatabase)]
go
insert into
	[Valid].[LearningProvider]
		(
			[UKPRN]
		)
select
	[UKPRN]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearningProvider]
where
	[LearningProvider].[UKPRN]=$(UKPRN)
go

insert into
	[Valid].[Learner]
		(
			[LearnRefNumber],
			[DateOfBirth]
		)
select
	[LearnRefNumber],
	[DateOfBirth]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[Learner]
where
	[Learner].[UKPRN]=$(UKPRN)
go

insert into
	[Valid].[LearningDelivery]
		(
			[LearnRefNumber],
			[AimSeqNumber],
			[AchDate],
			[AddHours],
			[CompStatus],
			[ConRefNumber],
			[LearnActEndDate],
			[LearnAimRef],
			[LearnPlanEndDate],
			[LearnStartDate],
			[LrnDelFAM_LDM1],
			[LrnDelFAM_LDM2],
			[LrnDelFAM_LDM3],
			[LrnDelFAM_LDM4],
			[LrnDelFAM_RES],
			[OrigLearnStartDate],
			[OtherFundAdj],
			[Outcome],
			[PriorLearnFundAdj],
			[FundModel]
		)
select
	[LearnRefNumber],
	[AimSeqNumber],
	[AchDate],
	[AddHours],
	[CompStatus],
	[ConRefNumber],
	[LearnActEndDate],
	[LearnAimRef],
	[LearnPlanEndDate],
	[LearnStartDate],
	[LrnDelFAM_LDM1],
	[LrnDelFAM_LDM2],
	[LrnDelFAM_LDM3],
	[LrnDelFAM_LDM4],
	[LrnDelFAM_RES],
	[OrigLearnStartDate],
	[OtherFundAdj],
	[Outcome],
	[PriorLearnFundAdj],
	[FundModel]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearningDeliveryDenorm] LearningDelivery
where
	[LearningDelivery].[UKPRN]=$(UKPRN)
go

insert into
	[Valid].[DPOutcome]
		(
			[LearnRefNumber],
			[OutType],
			[OutCode],
			[OutStartDate],
			[OutCollDate],
			[OutEndDate]
		)
select
	[LearnRefNumber],
	[OutType],
	[OutCode],
	[OutStartDate],
	[OutCollDate],
	[OutEndDate]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[DPOutcome]
where
	[DPOutcome].[UKPRN]=$(UKPRN)
go

