-- =====================================================================================================
-- Generated by Data Dictionary Version 1.0.0.0
-- Date: 08 April 2016 14:18
-- Profile: 1516 Test Harness Calculation
-- Rulebase Version: DCSS 1516 ESF Funding Calc 1516, Drop 000, Version 1516.13
-- =====================================================================================================
use [$(IntrajobDatabase)]
go
insert into
	[Input].[LearningProvider]
		(
			[LearningProvider_Id],
			[UKPRN]
		)
select
	[PK_LearningProvider],
	[UKPRN]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearningProvider]
go

insert into
	[Input].[Learner]
		(
			[Learner_Id],
			[LearnRefNumber],
			[DateOfBirth]
		)
select
	[PK_Learner],
	[LearnRefNumber],
	[DateOfBirth]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[Learner]
go

insert into
	[Input].[LearningDelivery]
		(
			[LearningDelivery_Id],
			[AimSeqNumber],
			[Learner_Id],
			[AchDate],
			[AddHours],
			[CompStatus],
			[ConRefNumber],
			[LearnActEndDate],
			[LearnAimRef],
			[LearnPlanEndDate],
			[LearnStartDate],
			[OrigLearnStartDate],
			[OtherFundAdj],
			[Outcome],
			[PriorLearnFundAdj],
			[FundModel]
		)
select
	[PK_LearningDelivery],
	[AimSeqNumber],
	[FK_Learner],
	[AchDate],
	[AddHours],
	[CompStatus],
	[ConRefNumber],
	[LearnActEndDate],
	[LearnAimRef],
	[LearnPlanEndDate],
	[LearnStartDate],
	[OrigLearnStartDate],
	[OtherFundAdj],
	[Outcome],
	[PriorLearnFundAdj],
	[FundModel]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearningDelivery]
go

insert into
	[Input].[LearningDeliveryFAM]
		(
			[LearningDeliveryFAM_Id],
			[LearnDelFAMType],
			[LearningDelivery_Id],
			[LearnDelFAMDateFrom],
			[LearnDelFAMCode]
		)
select
	[PK_LearningDeliveryFAM],
	[LearnDelFAMType],
	[FK_LearningDelivery],
	[LearnDelFAMDateFrom],
	[LearnDelFAMCode]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearningDeliveryFAM]
go

insert into
	[Input].[DPOutcome]
		(
			[DPOutcome_Id],
			[OutType],
			[LearnerDestinationandProgression_Id],
			[OutCode],
			[OutStartDate],
			[OutCollDate],
			[OutEndDate]
		)
select
	[PK_DPOutcome],
	[OutType],
	[FK_LearnerDestinationandProgression],
	[OutCode],
	[OutStartDate],
	[OutCollDate],
	[OutEndDate]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[DPOutcome]
go

insert into
	[Input].[LearnerDestinationandProgression]
		(
			[LearnerDestinationandProgression_Id],
			[LearnRefNumber]
		)
select
	[PK_LearnerDestinationandProgression],
	[LearnRefNumber]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearnerDestinationandProgression]
go

