-- =====================================================================================================
-- Generated by Data Dictionary Version 1.0.0.0
-- Date: 21 July 2015 10:40
-- Profile: 1516 Test Harness Validation
-- Rulebase Version: DCSS 1516 Validation FD 1516, Drop 000, Version 1516.04
-- =====================================================================================================
use [Intrajob_1516]
GO
if not exists(select schema_id from sys.schemas where name='Rulebase')
	exec('create schema Rulebase')
GO
if object_id('[Rulebase].[VALFD_Cases]','u') is not null
	drop table [Rulebase].[VALFD_Cases]
create table [Rulebase].[VALFD_Cases]
	(
		[Learner_Id] [int] primary key,
		[CaseData] [xml] not null
	)
GO
if object_id('[Rulebase].[VALFD_global]','u') is not null
	drop table [Rulebase].[VALFD_global]
create table [Rulebase].[VALFD_global]
	(
		[UKPRN] int,
		[RulebaseVersion] varchar(10),
	)
GO
if object_id('[Rulebase].[VALFD_ValidationError]','u') is not null
	drop table [Rulebase].[VALFD_ValidationError]
create table [Rulebase].[VALFD_ValidationError]
	(
		[AimSeqNumber] bigint,
		[ErrorString] varchar(2000),
		[FieldValues] varchar(2000),
		[LearnRefNumber] varchar(100),
		[RuleId] varchar(50)
	)
GO
