-- =====================================================================================================
-- Generated by Data Dictionary Version 1.0.0.0
-- Date: 28 July 2016 08:04
-- Profile: 1516 Test Harness Calculation
-- Rulebase Version: ILR Trailblazer Funding Calculation 1617, Drop 000, Version 1617.02
-- =====================================================================================================
use [$(IntrajobDatabase)]
go
insert into [Input].[LearningProvider] (
	[LearningProvider_Id],
	[UKPRN]
)
select
	[PK_LearningProvider],
	[UKPRN]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearningProvider]
go

insert into [Input].[Learner] (
	[Learner_Id],
	[LearnRefNumber],
	[DateOfBirth],
	Ethnicity,
	Sex,
	LLDDHealthProb,
	ULN
)
select
	[PK_Learner],
	[LearnRefNumber],
	[DateOfBirth],
	Ethnicity,
	Sex,
	LLDDHealthProb,
	ULN
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[Learner]
go

insert into [Input].[LearningDelivery] (
	[LearningDelivery_Id],
	[Learner_Id],
	LearnRefNumber,
	[AimSeqNumber],
	[AchDate],
	[AimType],
	[CompStatus],
	[LearnAimRef],
	[LearnActEndDate],
	[LearnPlanEndDate],
	[LearnStartDate],
	[OrigLearnStartDate],
	[OtherFundAdj],
	[Outcome],
	[PriorLearnFundAdj],
	[ProgType],
	[StdCode],
	[WithdrawReason],
	[FundModel]
)
select
	[PK_LearningDelivery],
	[FK_Learner],
	Learner.LearnRefNumber,
	[AimSeqNumber],
	[AchDate],
	[AimType],
	[CompStatus],
	[LearnAimRef],
	[LearnActEndDate],
	[LearnPlanEndDate],
	[LearnStartDate],
	[OrigLearnStartDate],
	[OtherFundAdj],
	[Outcome],
	[PriorLearnFundAdj],
	[ProgType],
	[StdCode],
	[WithdrawReason],
	[FundModel]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearningDelivery]
		join [$(FromILRDatabase)].[$(FromILRSchema)].Learner
			on Learner.PK_Learner = LearningDelivery.FK_Learner
go

insert into [Input].[LearningDeliveryFAM] (
	[LearningDeliveryFAM_Id],
	[LearningDelivery_Id],
	LearnRefNumber,
	AimSeqNumber,
	[LearnDelFAMType],
	[LearnDelFAMDateFrom],
	[LearnDelFAMCode],
	[LearnDelFAMDateTo]
)
select
	[PK_LearningDeliveryFAM],
	[FK_LearningDelivery],
	Learner.LearnRefNumber,
	AimSeqNumber,
	[LearnDelFAMType],
	[LearnDelFAMDateFrom],
	[LearnDelFAMCode],
	[LearnDelFAMDateTo]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearningDeliveryFAM]
		join [$(FromILRDatabase)].[$(FromILRSchema)].LearningDelivery
			on LearningDelivery.PK_LearningDelivery = LearningDeliveryFAM.FK_LearningDelivery
		join [$(FromILRDatabase)].[$(FromILRSchema)].Learner
			on Learner.PK_Learner = LearningDelivery.FK_Learner
go

insert into [Input].[AppFinrecord] (
	[AppFinRecord_Id],
	[LearningDelivery_Id],
	[LearnRefNumber],
	[AFinType],
	[AFinAmount],
	[AFinCode],
	[AFinDate]
)
select
	AppFinRecord.[PK_AppFinRecord],
	AppFinRecord.[FK_LearningDelivery],
	Learner.[LearnRefNumber],
	AppFinRecord.[AFinType],
	AppFinRecord.[AFinAmount],
	AppFinRecord.[AFinCode],
	AppFinRecord.[AFinDate]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[AppFinRecord]
	JOIN
		 [$(FromILRDatabase)].[$(FromILRSchema)].LearningDelivery 
			ON LearningDelivery.PK_LearningDelivery = AppFinRecord.FK_LearningDelivery
	JOIN
		[$(FromILRDatabase)].[$(FromILRSchema)].Learner
			ON Learner.PK_Learner = LearningDelivery.[FK_Learner]
GO

insert into [Input].[LearnerEmploymentStatus] (
	[LearnerEmploymentStatus_Id],
	[Learner_Id],
	LearnRefNumber,
	[DateEmpStatApp],
	[EmpId],
	[EmpStat]
)
select
	[PK_LearnerEmploymentStatus],
	[FK_Learner],
	Learner.LearnRefNumber,
	[DateEmpStatApp],
	[EmpId],
	[EmpStat]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearnerEmploymentStatus]
		join [$(FromILRDatabase)].[$(FromILRSchema)].Learner
			on Learner.PK_Learner = LearnerEmploymentStatus.FK_Learner
go

insert into [Input].[EmploymentStatusMonitoring] (
	[EmploymentStatusMonitoring_Id],
	[LearnerEmploymentStatus_Id],
	[LearnRefNumber],
	[ESMType],
	[ESMCode]
)
select
	[EmploymentStatusMonitoring].[PK_EmploymentStatusMonitoring],
	[EmploymentStatusMonitoring].[FK_LearnerEmploymentStatus],
	Learner.[LearnRefNumber],
	[EmploymentStatusMonitoring].[ESMType],
	[EmploymentStatusMonitoring].[ESMCode]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[EmploymentStatusMonitoring]
	JOIN [$(FromILRDatabase)].[$(FromILRSchema)].LearnerEmploymentStatus
		ON LearnerEmploymentStatus.PK_LearnerEmploymentStatus = EmploymentStatusMonitoring.FK_LearnerEmploymentStatus
	JOIN [$(FromILRDatabase)].[$(FromILRSchema)].Learner
			on Learner.PK_Learner = LearnerEmploymentStatus.FK_Learner
go

