-- =====================================================================================================
-- Generated by Data Dictionary Version 1.0.0.0
-- Date: 11 May 2016 11:56
-- Profile: 1516 Test Harness Validation
-- Rulebase Version: DCSS Validation DP 1617, Drop 000, Version 1617.01
-- =====================================================================================================
use [$(IntrajobDatabase)]
go
insert into
	[Input].[CollectionDetails]
		(
			[CollectionDetails_Id],
			[FilePreparationDate]
		)
select
	[PK_CollectionDetails],
	[FilePreparationDate]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[CollectionDetails]
go

insert into
	[Input].[LearningProvider]
		(
			[LearningProvider_Id],
			[UKPRN]
		)
select
	[PK_LearningProvider],
	[UKPRN]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearningProvider]
go

insert into
	[Input].[LearnerDestinationandProgression]
		(
			[LearnerDestinationandProgression_Id],
			[LearnRefNumber],
			[ULN]
		)
select
	[PK_LearnerDestinationandProgression],
	[LearnRefNumber],
	[ULN]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[LearnerDestinationandProgression]
go

insert into
	[Input].[DPOutcome]
		(
			[DPOutcome_Id],
			[OutCode],
			[OutCollDate],
			[OutEndDate],
			[OutStartDate],
			[OutType]
		)
select
	[PK_DPOutcome],
	[OutCode],
	[OutCollDate],
	[OutEndDate],
	[OutStartDate],
	[OutType]
from
	[$(FromILRDatabase)].[$(FromILRSchema)].[DPOutcome]
go

