-- =====================================================================================================
-- Generated by Data Dictionary Version 1.0.0.0
-- Date: 11 May 2016 11:56
-- Profile: 1516 Test Harness Validation
-- Rulebase Version: DCSS Validation DP 1617, Drop 000, Version 1617.01
-- =====================================================================================================
use [$(IntrajobDatabase)]
GO
if not exists(select schema_id from sys.schemas where name='Rulebase')
	exec('create schema Rulebase')
GO
if object_id('[Rulebase].[VALDP_Cases]','u') is not null
	drop table [Rulebase].[VALDP_Cases]
create table [Rulebase].[VALDP_Cases]
	(
		[LearnerDestinationAndProgression_Id] [int] primary key,
		[CaseData] [xml] not null
	)
GO
if object_id('[Rulebase].[VALDP_global]','u') is not null
	drop table [Rulebase].[VALDP_global]
create table [Rulebase].[VALDP_global]
	(
		[UKPRN] int,
		[OrgVersion] varchar(50),
		[RulebaseVersion] varchar(10),
		[ULNVersion] varchar(50)
	)
GO
if object_id('[Rulebase].[VALDP_ValidationError]','u') is not null
	drop table [Rulebase].[VALDP_ValidationError]
create table [Rulebase].[VALDP_ValidationError]
	(
		[ErrorString] varchar(2000),
		[FieldValues] varchar(2000),
		[LearnRefNumber] varchar(100),
		[RuleId] varchar(50)
	)
GO
