-- =====================================================================================================
-- Generated by Data Dictionary Version 1.0.0.0
-- Date: 04 January 2016 07:51
-- Profile: 1516 Test Harness Validation
-- Rulebase Version: DCSS 1516 Validation Learner 1516, Drop 000, Version 1516.16
-- =====================================================================================================
use [Intrajob_1516]
GO
if not exists(select schema_id from sys.schemas where name='Rulebase')
	exec('create schema Rulebase')
GO
if object_id('[Rulebase].[VAL_Cases]','u') is not null
	drop table [Rulebase].[VAL_Cases]
create table [Rulebase].[VAL_Cases]
	(
		[Learner_Id] [int] primary key,
		[CaseData] [xml] not null
	)
GO
if object_id('[Rulebase].[VAL_global]','u') is not null
	drop table [Rulebase].[VAL_global]
create table [Rulebase].[VAL_global]
	(
		[UKPRN] int,
		[RulebaseVersion] varchar(10),
		[OrgVersion] varchar(50),
		[PostcodeVersion] varchar(50),
		[EmployerVersion] varchar(50),
		[LARSVersion] varchar(50)
	)
GO
if object_id('[Rulebase].[VAL_ValidationError]','u') is not null
	drop table [Rulebase].[VAL_ValidationError]
create table [Rulebase].[VAL_ValidationError]
	(
		[AimSeqNumber] bigint,
		[ErrorString] varchar(2000),
		[FieldValues] varchar(2000),
		[LearnRefNumber] varchar(100),
		[RuleId] varchar(50)
	)
GO
